### PR TITLE
make the Model section of the lesson7-CAM work

### PR DESCRIPTION
**Pull request by stas00**
- fix the mismatch of 12 layer groups and lrs
- fix the accuracy_np code which expected non-log input

for discussion see:
http://forums.fast.ai/t/lesson7-cam-mismatch-between-of-lrs-and-of-layer-groups/19425

### CODE REVIEW

**Comment by stas00** [comment]
Jeremy, could you also please address why the 3 -> 12 lrs "broadcasting" doesn't work here, perhaps in this thread:

http://forums.fast.ai/t/lesson7-cam-mismatch-between-of-lrs-and-of-layer-groups/19425

**Comment by jph00** [comment]
@stas00 absolutely. Sorry about that - I haven't been coding for the last few months due to medical issues at home, so not surprised to hear that some notebooks have gotten out of sync with the PRs coming in. I'm back at work now so feel free to reach out directly if I miss anything. I'll ask @sgugger to look at this one.

**Comment by sgugger** [comment]
I have to review the notebook but I guess it would be better to define a proper layer_groups at the model level than pass 12 learning rates. I'll get on it later today.

**Comment by stas00** [comment]
Thank you, @jph00 and @sgugger, for working on that!

**Pull request merged**
