### PR TITLE
Update README to include CG and COC

### PR DESCRIPTION
**Pull request by odysseus0**
Updated README to include links to contribution guideline and code of conduct.

Added Jeremy's notes from the [About the fastai dev category](https://forums.fast.ai/t/about-the-fastai-dev-category/19546) to the contribution guideline. I just read it and found it super helpful; had I read the note earlier, I would have made fewer mistakes getting started as a new contributor. Currently the post is a bit obscure and hard to find, so it might help to include it directly here.

### CODE REVIEW

**Comment by stas00** [comment]
Thank you, @odysseus0! These were very useful additions.

**Comment by stas00** [comment]
I think it's a good idea to migrate some of the notes in forums to a corresponding fastai docs, often it's very difficult to find some of those gems in the forums.

**Comment by odysseus0** [comment]
Do you have any recommendations on where in the forum to look into? I would be more than willing to migrate them to fitting places, either here or in the docs.fast.ai.

**Comment by stas00** [comment]
Let's continue in the thread dedicated to this topic:
https://forums.fast.ai/t/documentation-improvements/32550/41

**Pull request merged**
