### PR TITLE
Interpret docs

### PR DESCRIPTION
**Pull request by KeremTurgutlu**
## Changes

- With regards to #2119 changed `probs` back to `preds`
- Tested course notebooks wherever `Interpretation` is used
- Ran all tests with `pytest`
- Added docs for new features and some of old ones 
- Ran `doc_src` notebooks manually to test

## TODOs

- Add test suite for `SegmentationInterpretation`

### CODE REVIEW

**Comment by sgugger** [comment]
Great work, thanks!

**Comment by KeremTurgutlu** [comment]
Thanks a lot! It looks like new docs_src notebooks `vision.interpret` and `text.interpret` are not visible in https://docs.fast.ai/ but other changes are reflected. What might be the reason for this? Was there any additional step that I've missed for adding new doc notebooks?

**Comment by sgugger** [comment]
Oh, they were there. I just forgot to run the script that makes the sidebar to have it updated. Done now :)

**Comment by KeremTurgutlu** [comment]
Cool, thanks! Now looking at the docs I see more things to fix, will do it as soon as possible :)

**Comment by pyjaime** [comment]
hey @KeremTurgutlu,

I see you updated the parameter again from probs to preds. That's ok, but you didn't update the references to ClassificationInterpretation, again. 

Check https://github.com/fastai/fastai/issues/2118 and read the bug carefully. You have to edit fastai/vision/learner.py **at least** (look for *probs*!). Don't know how you *"Tested course notebooks wherever Interpretation is used"* but you have to be more cautious.

**Comment by KeremTurgutlu** [comment]
hey @pyjaime thanks for this! Functions in `learner.py` still had probs as you mentioned. I actually ran all the course-v3 with interpretation and all the tests. I would say fastai that been used in notebook might be not my edited version? But then I even added new notebooks with new features and they ran just fine. Anyway, it's hopefully fixed now.

Besides this is dev branch for a reason, it allows us to catch each other's bugs of earlier 😄 Thanks again.

**Comment by pyjaime** [comment]
Hello!

The version of fastai used by the notebooks depends on you and your environment. 
Since those are on a different project maybe you ran them against another version.

Anyway, thank you for the quick fix. You're right with the last paragraph :)

**Pull request merged**
