### PR TITLE
GPU / CPU compatibility

### PR DESCRIPTION
**Pull request by sampathweb**
I created a new function `to_gpu` in `core.py` that checks if `cuda` is available and transfers the model or tensor to GPU.  Otherwise keeps the model / tensor in CPU.  This makes the code compatible for both GPU and CPU.   The API of `to_gpu` is desiged after `to_np` that's there in `core.py`.

### CODE REVIEW

**Comment by apiltamang** [comment]
i think it's a decent start. I've always wondered why PyTorch makes it hard to separate the logic between GPU and CPU in this manner.

I will test your commit out, and if you're cool, I might add in a support for multi-gpu resource utilization. PyTorch makes using multi-gpu super-easy, so maybe worth giving it a shot. But, instead of utilizing all GPUs by default, wonder how hard it might be to specify how many GPU's to use!

**Comment by yanneta** [comment]
Ramesh,
Have you test the code with and without GPU to make sure it works?

Best,
Yannet

**Comment by sampathweb** [comment]
@apiltamang - I would prefer to leave out the multi-gpu support out of this Pull request.  This pull request is intended to make fastai work both in CPU and GPU.  Adding multi-gpu might be better served in a separate pull request.

**Comment by sampathweb** [comment]
@yanneta - Thanks for reviewing my pull request.  I am working on it now to test with the New AMI that Jeremy has created.  I will confirm here once I run through couple of lesson notebooks in courses/dl1

**Comment by sampathweb** [comment]
@yanneta - I tested it on an P2 GPU instance using the AMI that Jeremy created for the course.  I ran the lesson1.ipynb for the dogs/cats notebook.

**Comment by yanneta** [comment]
Ramesh,
I am experiencing a slower notebook than before. I am not sure this is due to your changes but I want to investigate before merging. I will be working on this later today. Thanks!

**Comment by yanneta** [comment]
I merge the changes. Thank you!

**Comment by Coderx7** [comment]
The current implementation needs to also check for old gpus. Currently if a system has both CUDA and cuDNN installed but uses a GPU with compute capability <3 will result in failure while all the checks are seemingly OK. Incorporating a simple check such as this should solve the issue
```
def is_gpu_supported():
    for d in range(torch.cuda.device_count()):
        capability = torch.cuda.get_device_capability(d)[0]
        return False if capability < 3 else True
```

**Comment by Coderx7** [comment]
The current implementation needs to also check for old GPUs. Currently if a system has CUDA and cuDNN installed but has a GPU with compute capability <3, it results in failure, while all the checks are seemingly fine! Incorporating a simple check like the one below should fix this issue : 
```
def is_gpu_supported():
    for d in range(torch.cuda.device_count()):
        capability = torch.cuda.get_device_capability(d)[0]
        return False if capability < 3 else True

USE_GPU = torch.cuda.is_available()
def to_gpu(x, *args, **kwargs):
    '''puts pytorch variable to gpu, if cuda is available and USE_GPU is set to true. '''
    return x.cuda(*args, **kwargs) if (USE_GPU and is_gpu_supported()) else x
```

**Pull request merged**
