### PR TITLE
Add show_top_losses() to TextClassificationInterpretation

### PR DESCRIPTION
**Pull request by thousfeet**
Enhance TextClassificationInterpretation by adding `show_top_losses()`, inspired by `plot_top_losses` in vision.learn.
This method creates a tabulation that shows texts in `top_losses` along with their prediction, actual, loss, and probability of actual class.
Also, I made `TextClassificationInterpretation` inherit `ClassificationInterpretation` so that all methods in `ClassificationInterpretation` can be called by `TextClassificationInterpretation` instance.

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks a lot. One thigns annoy me, and it's the added dependency. Can you put your table in a dataframe instead? If you look at `show_xy` in `TextList`, you'll see we show the data by putting it in a dataframe `df` then going
```
with pd.option_context('display.max_colwidth', -1):
    display(HTML(df.to_html(index=False)))
```
It would be great if you could use the same here as it would make it consistent with the rest of the library.

**Comment by bfarzin** [comment]
Will you also please add to the docs?

**Comment by thousfeet** [comment]
> 
> 
> Will you also please add to the docs?

Yes, with pleasure. I'll write them after this PR be merged.

**Comment by thousfeet** [comment]
> 
> 
> Thanks a lot. One thigns annoy me, and it's the added dependency. Can you put your table in a dataframe instead? If you look at `show_xy` in `TextList`, you'll see we show the data by putting it in a dataframe `df` then going
> 
> ```
> with pd.option_context('display.max_colwidth', -1):
>     display(HTML(df.to_html(index=False)))
> ```
> 
> It would be great if you could use the same here as it would make it consistent with the rest of the library.

I've rewrote it and discarded dependency. Now the table looks like this:
图片

**Comment by sgugger** [comment]
Thanks a lot. For future reference, don't forget to run
```
tools/run-after-git-clone
```
before making PRs with the docs notebooks, as it will automatically strip them of unnecessary metadata when you commit. That's why you had a failing test.

**Comment by thousfeet** [comment]
> 
> 
> Thanks a lot. For future reference, don't forget to run
> 
> ```
> tools/run-after-git-clone
> ```
> 
> before making PRs with the docs notebooks, as it will automatically strip them of unnecessary metadata when you commit. That's why you had a failing test.

Sure, thanks!

**Comment by mrdbourke** [comment]
Massive update @thousfeet! Thank you for this.

However, I'm running into an issue when I try to use it?

```
AttributeError                            Traceback (most recent call last)
<ipython-input-144-1aad6567562c> in <module>
----> 1 txt_ci.show_top_losses(5)

AttributeError: 'TextClassificationInterpretation' object has no attribute 'show_top_losses'
```

I've uninstalled fastai via pip uninstall, and reinstalled it.

Potentially I have to build from source?

**Pull request merged**
