### PR TITLE
Handle timouts in download_url

### PR DESCRIPTION
**Pull request by bfarzin**
* Handle the timeouts for `download_url` to retry 5 times.  If failed, raise a verbose message about how to manually download.
* Added `force_download` param to `untar_data`
* Added test to `test_vision_data.py` to handle partial-download of tar file.  Returns sensible message about what broke.

Please let me know if there are any stylistic improvements. This is my first PR touching code (that is, beyond doc examples) and I tried to be concise with the code style but it might not be what you are looking for.

### CODE REVIEW

**Comment by stas00** [comment]
Well, my emacs is set to remove any extraneous spaces, and adding new lines at the end of the file. I don't think the other developers have that, but their editors aren't set to add empty whitespace, so these occasionally leak into the code here and there.

I usually try to make a separate commit when I see a lot of non-code-related changes happen, so it's easy to see the actual code change.

Also, your PR got out of sync and needed a merge, so that was my last commit I pushed into this PR.

Just waiting on CI's confirmation and will merge then.

**Comment by stas00** [comment]
hmm, looks like I messed something up bypassing the github interface and merging from shell. Give me a few minutes to sort it out.

**Comment by stas00** [comment]
All is well. I'm just still sorting out how to with github PRs w/o using its online interface.

Everything has been merged.

Thank you for sorting it out and very importantly the test that tests this improvement, @bfarzin

**Comment by bfarzin** [comment]
Very happy to be helping out in a small way.

**Pull request merged**
