### PR TITLE
Fixes the QRNN performance issue when no split_fn is provided during learner construction.

### PR DESCRIPTION
**Pull request by PiotrCzapla**
The PR adds two tests but they can be run only if you have a cupy installed to pinpoint the issue.
It also fixes the issue by calling reset() during the init of WeightsDrops:
7706e22

But It isn't the best idea since it may cause case-cading resets during initialization, so I've changed it to simply execute relevant part of the reset function without propagating the reset call it down the tree.
d60adca

it replaces this PR https://github.com/fastai/fastai/pull/1135

### CODE REVIEW

**Comment by sgugger** [comment]
Please amend your PR to be able to merge with the latest big refactor. If it's easiest, close this one and reopen another.

**Comment by sgugger** [comment]
I tried to move the reset call in post_init of Sequential as it would be cleaner to do it there. I'll try and revert if that breaks anything. Thanks for your PR!

**Comment by PiotrCzapla** [comment]
> I tried to move the reset call in post_init of Sequential as it would be cleaner to do it there. I'll try and revert if that breaks anything. Thanks for your PR!

I've thought that `__post_init__` works only in `dataclasses` and `nn.Module` is not one of them, or maybe I'm missing something. But either way, since the reset call is fixed I can run it if needed my self.

**Comment by sgugger** [comment]
Yeah, it doesn't properly work. I'll edit and change soon-ish, I'm currently fixing the tests.

**Pull request merged**
