### PR TITLE
`img_size` attribute for `TensorPoint` is not updated properly

### PR DESCRIPTION
**Pull request by IRailean**
Solving the issue reported in #2786 
As resized image size will be saved in PointScaler self.sz variable, and 'img_size' attribute for TensorPoint is not updated properly -> prioritize self.sz over sz in PointScaler _get_sz function.

### CODE REVIEW

**Comment by jph00** [comment]
Could you please add a test in the notebook that previously would have failed, but this change makes pass?

**Review by jph00 — CHANGES_REQUESTED** [review]
Could you please add a test in the notebook that previously would have failed, but this change makes pass?

**Comment by IRailean** [comment]
I have updated the last test from 09_vision.augment.ipynb with a new transform Resize(256) - it is clearly seen that previously bboxes are not covering the objects. 
Note: With the old implementation everything works fine if run only this notebook. If run after installing fastai (pip | from git | using local setup.py), bboxes are not shown correctly.

**Comment by jph00** [comment]
> With the old implementation everything works fine if run only this notebook. If run after installing fastai (pip | from git | using local setup.py), bboxes are not shown correctly.

Oh interesting - can you tell me more about this? Is it a fastcore change or fastai change which broke things? Do you know what version the breakage occurred from?

**Comment by marii-moe** [comment]
I think I was the one who originally stated that a previous version existed that did not have the issue. I tried to track down the issue, but didn't get to the bottom of it yet. This notebook shows the behavior I found that was suspicious: https://gist.github.com/marii-moe/a8e7a330fbd4d9b0dc326e396ef17e36

Note, in the above notebook the gist is from a recent version of fastai, I copied and pasted the results from the previous version for a comparison. 

commit that this is from is 94e1568f9d9f7718a8c925436fc4b25452f626b9

**Comment by jph00** [comment]
Thanks to you both! I'll just go ahead and merge this then, but I don't actually know if it's the right fix, so I'd love it if you folks could take a look at some image augmentation outputs and confirm visually that it all looks ok to you! :)

**Comment by muellerzr** [comment]
Can confirm this is working. Also fixes any issues with `aug_transforms` along with it. Nice work guys :)

**Pull request merged**
