### PR TITLE
Steps to resolve error fastai.structured not found

### PR DESCRIPTION
**Pull request by Priyansi**
When this notebook is run on Google Colab, an error is thrown - ModuleNotFoundError: No module named 'fastai.structured'
I have tested and provided steps in the form of an additional markdown block to resolve this error for the students new to the ML course.
#2609 Fix for this issue.

### CODE REVIEW

**Comment by rahul9d** [comment]
thanks a lot :-)

**Comment by kunalrustagi08** [comment]
> When this notebook is run on Google Colab, an error is thrown - ModuleNotFoundError: No module named 'fastai.structured'
> I have tested and provided steps in the form of an additional markdown block to resolve this error for the students new to the ML course.
Nice work but I feel this is way shorter 
`pip install "git+https://github.com/fastai/fastai#egg=fastai&subdirectory=old"`

**Comment by Priyansi** [comment]
> `pip install "git+https://github.com/fastai/fastai#egg=fastai&subdirectory=old"`

Are you talking about replacing this? -
```python
!pip install torchvision==0.1.9
!pip install fastai==0.7.0
!pip install torchtext==0.2.3
```
For the Import Imputer error still persists without changing structured.py

Still learning :)

**Comment by kunalrustagi08** [comment]
Okay so in the end, it is just the same!  
Same, still learning ;)

**Comment by kunalrustagi08** [comment]
> For the Import Imputer error still persists without changing structured.py  

If I continue to run the notebooks in google colab, I need to add the import imputer everytime to the structured.py?

**Comment by M-Salti** [comment]
The `Imputer` error has already been solved 4 months ago in this commit: https://github.com/fastai/fastai/commit/3b54ef1575f941721c7d5ec4011ebaf51cd06eeb.
To solve https://github.com/fastai/fastai/issues/2609 you need to install fastai 0.7.0, which you can do either like this:
```bash
git clone https://github.com/fastai/fastai.git
pip install ./fastai/old/.
```
or like this (for Google Colab you must first uninstall the previously installed version of fastai):
```
!pip uninstall fastai
!pip install "git+https://github.com/fastai/fastai#egg=fastai&subdirectory=old"
```
Both of these two methods will get you the latest commit of fastai so you won't face the `Imputer` import error.

**Comment by ghosh-r** [comment]
Try importing from `fastai.tabular` instead of `fastai.structured`.

`fastai.structured` methods are moved to `fastai.tabular`.

So,

```python
from fastai.tabular import *
```

will do the job.

**Comment by jph00** [comment]
We're not able to accept this PR, since the diff is changing every line of the notebook. Please only change the minimum number of lines for what you're adding.

**Pull request closed without merging**
