### PR TITLE
fix visible show_doc in some of the documentation

### PR DESCRIPTION
**Pull request by pouannes**

### CODE REVIEW

**Comment by pouannes** [comment]
Not really sure why the check failed, I only went through some cells checking "hide input" when necessary

**Comment by Benudek** [comment]
sth bout stripping, see here: https://dev.azure.com/fastdotai/fastai/_build/results?buildId=2488

**Comment by pouannes** [comment]
I thought I ran the stripper tool, I'll double check thanks

**Comment by pouannes** [comment]
Thanks for the encouragement Sylvain ! I thought I ran tools/run-after-git-clone but I must have forgotten after another clone. Hopefully it's all good now :)

**Comment by sgugger** [comment]
It is! Congrats on your first PR merged and thanks for the help!

**Comment by stas00** [comment]
> Thanks for the encouragement Sylvain ! I thought I ran tools/run-after-git-clone but I must have forgotten after another clone. Hopefully it's all good now :)

Use the helper program that will clone, branch and set it all up, including running  `tools/run-after-git-clone` automatically for you: https://docs.fast.ai/dev/git.html#helper-program

**Comment by stas00** [comment]
> sth bout stripping, see here: https://dev.azure.com/fastdotai/fastai/_build/results?buildId=2488

The "sth" is explained here:
https://docs.fast.ai/dev/develop.html#after-git-clone-1-a-mandatory-notebook-strip-out

**Pull request merged**
