### PR TITLE
just a missing .. for the right directory after the cd fastai in the git.md

### PR DESCRIPTION
**Pull request by Benudek**

### CODE REVIEW

**Comment by Benudek** [comment]
Understand, thx ! Maybe good to also add this '**... add that path to the python libs path ...**' in the doc then. When I just followed the cmd steps (see below) I needed the .. ;-) And for those who the syntax '**.[dev]**' is somewhat unfamiliar (like for me) it takes a moment to figure out.

**> git clone https://github.com/fastai/fastai
> cd fastai**
--> add here sth like ... add a path to the python libs 
**> pip install -e .[dev]**

**Comment by stas00** [comment]
Please refer to https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs
and https://pip.pypa.io/en/stable/reference/pip_install/#examples

You don't need to do anything, just follow the instructions - it will just work.

**Comment by Benudek** [comment]
Hmm, I really did try to follow the instructions step by step on the cmd and ran into this issue. What do I miss - I don't seem to find a comment on adding sth in the path?

It's a super minor thing really, no blocker or alike - so I mute myself here :-)

**Comment by stas00** [comment]
The difficultly with this conversation is that you're not telling us what the problem is. You suggested a fix to a problem, but didn't explain what the problem is.

However, please, have a look at this new section I have just added. I have a feeling you were hit by a double installation problem discussed in that section.

https://docs.fast.ai/dev/develop.html#editable-install-explained

**Comment by Benudek** [comment]
**Error Message**: 
Directory '.' is not installable. File 'setup.py' not found.
**Steps to reproduce:**
execute Step 3. Prepare Your Checkout (https://docs.fast.ai/dev/git.html)

_(base) bherudek-ltm1:fastai-fork bherudek$ cd fastai
(base) bherudek-ltm1:fastai bherudek$ pip install -e .[dev]
Directory '.' is not installable. File 'setup.py' not found.
(base) bherudek-ltm1:fastai bherudek$_ 

Resolution:
(1) cd - before pip install
or go in below director
(2) pip install -e ..[dev]

**Comment by Benudek** [comment]
this new section https://docs.fast.ai/dev/develop.html#editable-install-explained looks helpful! thx 

Couldn't execute the conda activate step though:
- conda activate fastai
- Could not find conda environment: fastai
- You can list all discoverable environments with `conda info --envs`.

Will need to study that a little more though to understand the context and where it comes into the picture when working with the fast.ai code locally

**Comment by stas00** [comment]
> **Error Message**:
> Directory '.' is not installable. File 'setup.py' not found.
> **Steps to reproduce:**
> execute Step 3. Prepare Your Checkout (https://docs.fast.ai/dev/git.html)
> 
> _(base) bherudek-ltm1:fastai-fork bherudek$ cd fastai (base) bherudek-ltm1:fastai bherudek$ pip install -e .[dev] Directory '.' is not installable. File 'setup.py' not found. (base) bherudek-ltm1:fastai bherudek$_
> 
> Resolution:
> (1) cd - before pip install
> or go in below directory
> (2) pip install -e ..[dev]
> 
> or (as I understood from your comment): ' ... add that path to the python libs path ... '

That's better, thank you. As I suspected you are executing `cd fastai` twice and ending up inside `fastai` modules folder instead of the `fastai` project folder. I know it's confusing (the github user is `fastai` too!)
Have a look at the updated instructions, I used `fastai-fork` as a name for a checkout folder. 
Let me know if all is good now.

**Comment by Benudek** [comment]
All good, thx! Should Start with the issue description indeed

**Comment by stas00** [comment]
> this new section https://docs.fast.ai/dev/develop.html#editable-install-explained looks helpful! thx
> 
> Couldn't execute the conda activate step though:
> _(base) bherudek-ltm1:fastai-fork bherudek$ conda activate fastai Could not find conda environment: fastai You can list all discoverable environments with `conda info --envs`._
> 
> Will need to study that a little more though to understand the context and where it comes into the picture when working with the fast.ai code locally

I added a new section: https://docs.fast.ai/install.html#virtual-environment
If there are questions still please ask.

**Comment by Benudek** [comment]
great section on the virtual env!

When running through section 'Editable Install Explained' the below section with .[ indeed works. So I guess as you said before I must be cding once too often into the directory fastai

Anyways, good learning curve for me - thx for helping out

_cd ~/github
git clone https://github.com/fastai/fastai
cd fastai
pip install -e ".[dev]"_

**Comment by stas00** [comment]
I'm glad you sorted it out, @Benudek! Looking forward to your PRs.

**Pull request closed without merging**
