### PR TITLE
just a reminder to do pip install -e ...

### PR DESCRIPTION
**Pull request by Benudek**
name of branch misleading, this is just adding a print to not forget pip install ... 

I often forget and need some clicks into the docs and even raised an error for that, so we can avoid that maybe

### CODE REVIEW

**Comment by jph00** [comment]
Thanks!

**Comment by stas00** [comment]
This is incorrect. ".[dev]" applies only to the fastai repo.

**Comment by Benudek** [comment]
ok, sorry about that, took the text basically from the doc. What would be the correct text to qualify for ?

If helpful and you don't wanna correct directly, can make a simple PR.

**Comment by stas00** [comment]
it should check that both, the user and the repo are 'fastai' and only then suggest what your PR did.

**Pull request merged**
