### PR TITLE
fix(wandb): remove unused parameter

### PR DESCRIPTION
**Pull request by borisdayma**
Remove unused parameter which causes issue in future release of wandb

### CODE REVIEW

**Comment by borisdayma** [comment]
Actually I'm going to take advantage to implement another small improvement on model logging

**Comment by borisdayma** [comment]
The way to log model should be more robust, mainly if the saved model file changes while being uploaded (for example when using `fine_tune` on short epochs).

**Comment by borisdayma** [comment]
@jph00 Not sure if we're still supposed to tag you on PR's

**Comment by jph00** [comment]
I've got things better set up to notify me now. But feel free to tag me if you don't get a timely response

**Pull request merged**
