### PR TITLE
Add Starting Doc String to ConvLearner

### PR DESCRIPTION
**Pull request by Holisticnature**
Starting small with basic edits to give some type of description of the ConvLearner class. This is my first commit to the repo, and the code of conduct is specific to standards of behavior rather than expectations of commits. I just expect we can have  a small discussion about the change, and is also why I am starting small.

### CODE REVIEW

**Comment by jph00** [comment]
I think you could provide more detail. Maybe easier to document Learner first. A learner is something that combines a ModelData object with a nn.Module object, such that you can train that module with that data.

**Comment by Holisticnature** [comment]
Hi Jeremy,
I intended to add more detail to kwargs** potentially later (based on research into Learn() class). Do you want that done before this is committed to the main repo? 
I think this is better than leaving it blank, but I will add more detail as I get deeper.

**Comment by jph00** [comment]
I don't think you need to add more detail to kwargs yet - once you've documented the relevant bit of `Learner` you can then include a brief summary here.

**Comment by Holisticnature** [comment]
Understood. I will close this for now.

**Pull request closed without merging**
