### PR TITLE
Bug fix - Handle listy predictions in validate()

### PR DESCRIPTION
**Pull request by lharries**
preds.data means that validate() will error when a list of predictions is passed in (a similar problem to #644)

This fix is needed for when model is run on multiple inputs sequentially and hence has multiple predictions, e.g. when I was creating a Siamese network

This is a similar fix to #660

### CODE REVIEW

**Comment by lharries** [comment]
@sgugger would you mind looking at this, it's a similar fix to #660 which you previously approved.

**Comment by sgugger** [comment]
Mmm, when we start using the same code so many times, it means we need a helper function. I think the best solution is to write a function datafy that takes an object like preds/y and returns:
- preds.data if preds is not a list
- [o.data for o in preds] if preds is a list
Then all of this code will be simplified into 
res.append([f(datafy(preds), datafy(y)) for f in metrics)])
Can you modify your PR into something like that?

**Comment by lharries** [comment]
I've implemented datafy() as suggested, definitely looks cleaner!

**Comment by sgugger** [comment]
Great, thanks for your help!

**Pull request merged**
