### PR TITLE
More additions to the core docs.

### PR DESCRIPTION
**Pull request by bfarzin**
Examples, etc. through the `collection related` functions section

### CODE REVIEW

**Comment by stas00** [comment]
FYI, your pr includes errors, e.g.:

"/home/farzin/anaconda3/envs/fastaiv1_dev/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88\n",

**Comment by bfarzin** [comment]
Thank you for pointing this out.  I am still new to PRs. How do I debug this?

**Comment by mattip** [comment]
Hi. NumPy developer here, come to comment about the "changed size" warning. This happens when you have cythonized files with one version of NumPy, but at runtime are using another, later version of NumPy. Which library is emitting the warning? Does it have generated C files or binary shared objects from Cython checked into the repository? It would seem this is the case, since Cython 0.29 and up print a slightly different error `size changed, may indicate binary incompatibility. Expected %zd from C header, got %zd from PyObject`

**Comment by bfarzin** [comment]
I think the problem is coming from tarfile.py but I am really not sure.  I feel a bit out of place commenting on this.  How can I determine the source or the error?

```
../../anaconda3/envs/fastaiv1_dev/lib/python3.7/tarfile.py:2302: ReadError
=============================== warnings summary ===============================
/home/farzin/anaconda3/envs/fastaiv1_dev/lib/python3.7/importlib/_bootstrap.py:219
  /home/farzin/anaconda3/envs/fastaiv1_dev/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
    return f(*args, **kwds)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=== 6 failed, 171 passed, 7 skipped, 4 xfailed, 1 warnings in 198.01 seconds ===
Makefile:169: recipe for target 'test' failed
make: *** [test] Error 1

```

**Comment by stas00** [comment]
True, we just don't need "harmless" warnings in the documentation. It's possible that you identified a bug though in the code. That's the difficulty with writing documentation and tests, often these efforts lead to a lot more work, as inconsistencies and bugs get uncovered.

Which test is it coming from?

I've just retested py3.7 test suite - no warnings were emitted. But I do remember seeing some warning in the past.

As @mattip kindly shared, perhaps try:

```
pip uninstall -y numpy
pip uninstall -y numpy # 2nd time in case you also had "-e ." install
conda uninstall -y numpy
```
and then install just one of them?

**Comment by bfarzin** [comment]
the uninstall seems to have broken everything on my side.  let me try a fresh environment with the latest dev release, then copy the file over and see if my tests still fail.
FYI, numpy was 1.15.0 version.

**Comment by stas00** [comment]
Oh, very sorry about that. I guess I shouldn't have added -y to the instructions and, of course, conda happily uninstalled everything that depended on numpy. Ouch. Hopefully you still have the log and can just conda install what it uninstalled, which will quickly restore the original state.

Apologies, again.

**Comment by bfarzin** [comment]
No problem, we will figure it out from here.  Not sure this is the best place to debug this, please advise if I should move this discussion about install problems to the fasta.ai forums.

I could not recover my environment that was working.  I started a new conda environment that is clean and went into my fork of the repo:

```
$conda create --name fai_v1_dev python=3.7
$conda activate fai_v1_dev
$pip install -e ".[dev]"
```
Then to test out, I tried:
`jupyter nbconvert --execute --ExecutePreprocessor.timeout=600 --to notebook examples/tabular.ipynb`

That fails with:
```
from fastai.tabular import *  # Quick accesss to tabular functionality
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

However, I am able to go into a REPL and then import numpy, torch, etc. with no trouble.  Any ideas what is going on here?

```
Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 18:15:35) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.15.4'
>>> import torch
>>> torch.__version__
'1.0.0'
```

**Comment by bfarzin** [comment]
From [this forum post](https://forums.fast.ai/t/productionizing-models-thread/28353/78), I found that rolling back Bottleneck version worked.
`pip install Bottleneck==1.2.0`

I still have failing tests.  And I think that is associated (strangely) with a bad URL:

```
>                   raise ReadError("empty file")
E                   tarfile.ReadError: empty file

../../anaconda3/envs/fai_v1_dev/lib/python3.7/tarfile.py:2304: ReadError
========================== 6 failed, 171 passed, 7 skipped, 4 xfailed in 114.05 seconds ==========================
Makefile:169: recipe for target 'test' failed
make: *** [test] Error 1
```
when I try to `curl` to the URL, I get this:

```
farzin@lincoln:~/fast_ai/fastai-fork/tests$ curl http://files.fast.ai/data/examples/coco_tiny
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /data/examples/coco_tiny was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

This is what I am seeing as failing tests:
```
(fai_v1_dev) farzin@lincoln:~/fast_ai/fastai-fork$ make test
python setup.py --quiet test
warning: no files found matching 'HISTORY.md'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no files found matching 'conf.py' under directory 'docs'
warning: no files found matching 'Makefile' under directory 'docs'
warning: no files found matching 'make.bat' under directory 'docs'
============================================== test session starts ===============================================
platform linux -- Python 3.7.1, pytest-4.1.0, py-1.7.0, pluggy-0.8.1
rootdir: /home/farzin/fast_ai/fastai-fork, inifile: setup.cfg
collected 188 items                                                                                              

tests/test_basic_data.py ....                                                                              [  2%]
tests/test_batchnom_issue_minimal.py s.                                                                    [  3%]
tests/test_callback_fp16.py ...                                                                            [  4%]
tests/test_callbacks_csv_logger.py .                                                                       [  5%]
tests/test_callbacks_hooks.py .x....                                                                       [  8%]
tests/test_collab_train.py .                                                                               [  9%]
tests/test_core.py ...............................                                                         [ 25%]
tests/test_data_block.py ........                                                                          [ 29%]
tests/test_datasets.py .                                                                                   [ 30%]
tests/test_metrics.py ...............                                                                      [ 38%]
tests/test_tabular_train.py .....                                                                          [ 40%]
tests/test_tabular_transform.py ....                                                                       [ 43%]
tests/test_text_data.py ........                                                                           [ 47%]
tests/test_text_train.py ..ss..s.                                                                          [ 51%]
tests/test_text_transform.py ..                                                                            [ 52%]
tests/test_torch_core.py ...............                                                                   [ 60%]
tests/test_utils.py ..                                                                                     [ 61%]
tests/test_utils_fastai.py .                                                                               [ 62%]
tests/test_utils_links.py s........s.                                                                      [ 68%]
tests/test_utils_mem.py ....                                                                               [ 70%]
tests/test_utils_mod_independency.py .s                                                                    [ 71%]
tests/test_vision_data.py .............FFFF.F.F...                                                         [ 84%]
tests/test_vision_image.py ........                                                                        [ 88%]
tests/test_vision_train.py .........x                                                                      [ 93%]
tests/test_vision_transform.py ........                                                                    [ 97%]
tests/test_widgets_image_cleaner.py x.x.                                                                   [100%]

==================================================== FAILURES ====================================================
___________________________________________________ test_multi ___________________________________________________
```

**Comment by stas00** [comment]
The same thread further down suggests to install the latest numpy 1.16.0rc1 to solve the numpy issue
https://forums.fast.ai/t/productionizing-models-thread/28353/83
I looked through some similar reports, there is quite a flurry of those on github in the last few weeks. But none give a definitive way.

Why are you trying to download http://files.fast.ai/data/examples/coco_tiny? The url is:
http://files.fast.ai/data/examples/coco_tiny.tgz
I just removed `~/.fastai/data/coco_tiny.tgz` and `~/.fastai/data/coco_tiny` and when I run:

```
pytest tests/test_vision_data.py
```
it downloads it just fine and the test suceeds. 

Yes, let's close this, and continue over at: https://forums.fast.ai/t/fastai-v1-install-issues-thread/24111/261 so it may benefit others down the road. And once we sort out your setup then do another PR if this plan is agreeable with you, @bfarzin.

**Comment by bfarzin** [comment]
I posted to that thread and now have a version that passes all tests.  
I will submit a new PR passing all the tests.  Not sure how you want to handle the details about the latest install and conflict between Bottleneck and Numpy, but if there is a way I can help with that I am happy to do it.

**Comment by stas00** [comment]
Thank you for the report. I will investigate and follow up there. 

FYI, I split the 2nd part of your post to https://forums.fast.ai/t/developer-chat/22363/623 where it belongs as it's not an install issue.

**Pull request closed without merging**
