### PR TITLE
All plot functions return their figure

### PR DESCRIPTION
**Pull request by sotte**
All plot functions return the `plt.Figure`. This makes it easy to save the figures or tweak them to ones liking.

### CODE REVIEW

**Comment by sgugger** [comment]
Looks good, thanks for adding this!

**Comment by stas00** [comment]
Nope, this is not good at all.
e.g. this now prints 2 plots:
learn.recorder.plot()

**Comment by sgugger** [comment]
Ah, it didn't do what I thought it would. Yes returning the figure without a new flag won't work in notebooks, so I'll revert.
We can do this with an extra arg `return_fig:bool=None` that would default to `defaults.return_fig`, `False` by default. That way the user can easily control the default behavior globally but still override it when they want too. @sotte let me know if you want to do it.

**Comment by sotte** [comment]
Of course you're right, the current implementation breaks the workflow of many people. I'll create a new PR adjust the following:
- add a global `return_fig` to `defaults`
- add `return_fig` flag to all plot functions
- use the global `default.return_fig` if `return_fig is None` 

I did a test in a notebook and saw two plots, but added an `;` at the end of the line immediately without even thinking, just habit in these cases. Some people argue that showing every plot automatically in the notebook environment is a great feature, some people would prefer an explicit return :) I mostly work in IDEs/editors and the problem/the second plot is not visible there. 

Thanks @sgugger and @stas00!

**Pull request merged**
