### PR TITLE
fixing .md typo

### PR DESCRIPTION
**Pull request by alibaltschun**

### CODE REVIEW

**Comment by stas00** [comment]
Please sign this CLA agreement https://www.clahub.com/agreements/fastai/fastai as explained [here](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md) before we can proceed.  Thank you.

**Comment by alibaltschun** [comment]
sorry for that,  thanks for your time
@stas00

**Comment by stas00** [comment]
Thank you, @alibaltschun!

**Comment by alibaltschun** [comment]
welcome, @stas00

**Pull request merged**
