### PR TITLE
added documentation for torch_core.flatten

### PR DESCRIPTION
**Pull request by marii-moe**
This is my first pull request for the docs. Wanted to go ahead and get this one reviewed before making more contributions so I could get more of an idea of what we are trying to do here.

### CODE REVIEW

**Comment by marii-moe** [comment]
Seems there was some issue with "unstripped out notebook commits." Looking through the build pipeline to see what went wrong.

**Comment by stas00** [comment]
https://docs.fast.ai/dev/develop.html#things-to-run-after-git-clone

**Comment by marii-moe** [comment]
> https://docs.fast.ai/dev/develop.html#things-to-run-after-git-clone

I already seem to have the correct entries in my .git/config file. Will update if I find anything that looks amiss.

**Comment by stas00** [comment]
If you didn't do the setup correctly right away before committing, and enabled local .gitconfig afterwards, you need to repair the committed nb first:
https://docs.fast.ai/dev/develop.html#unstripped-notebook-repair

**Comment by marii-moe** [comment]
> If you didn't do the setup correctly right away before committing, and enabled local .gitconfig afterwards, you need to repair the committed nb first:
> https://docs.fast.ai/dev/develop.html#unstripped-notebook-repair

I did the run-after-git-clone step months ago to set the proper permissions, which is why I am surprised. I will go ahead and do the repair though and see if the problem persists afterwards.

**Comment by sgugger** [comment]
Thanks! If you properly ran tools/run-after-git-clone, the stripping should be done automatically from now on.

**Comment by sgugger** [comment]
Just one note: the function had been renamed `flatten_model` so I changed a little bit your notebook to reflect this.

**Pull request merged**
