### PR TITLE
Proposed fix for  #386 ImageClassifierData.from_csv does not select the rows corresponding to val_idxs even if explicitly passed.

### PR DESCRIPTION
**Pull request by sidchat04**
Fix for #386 

- First commit adds a regression test that can be helpful in demonstrating the issue. I have tried following the test guidelines, but it's still my first time writing tests in Python using pytest, so please let me know if anything needs to be changed.
 - Second commit attempts to fix the issue by introducing another parameter (sort_fnames) in methods used by ImageClassifierData.from_csv, that indicate whether the returned file names need to be sorted. The parameter is passed in as False, if the list of validation indexes has been provided. It is True by default.

Please let me know if any changes are required. Thanks.

### CODE REVIEW

**Comment by PiotrCzapla** [comment]
@sidchat04 I'm having a hard time understanding the issue. Do you mean that the order of the CSV file is not being kept?

**Comment by sidchat04** [comment]
@PiotrCzapla The problem is this: If I pass [2, 3] as the val_idxs parameter in from_csv method, I want rows with index 2 and 3 from the passed CSV to be chosen as my validation data. But since the list of file names has already been sorted by the time validation data is picked, the rows chosen are different.

This does not create a problem in cases when we are randomly generating the validation indexes. But in some cases, the validation data is also provided along with the problem (example is the Kaggle competition https://www.kaggle.com/c/imaterialist-challenge-furniture-2018/data).

**Comment by PiotrCzapla** [comment]
I see.  what I dont understand is why are we sorting the CSV file in the first place as the CSV has order that does not change. Maybe this is something coming from code where files are being read from file system and the order can change from time to time, @jph00 ?

**Comment by jph00** [comment]
Thanks this is very helpful! I must admit I'm not wondering why we're sorting the csv at all. It does seem like leaving it in the original order is most likely to be what's desired. Does anyone know of a reason that sorting is a good idea?

**Comment by sidchat04** [comment]
Possibly to be able to view the file names conveniently, but I am not so sure. I can easily undo my changes in the PR, and then remove the sorting.

**Comment by sidchat04** [comment]
@jph00 My apologies for not following up on this. I have now updated this PR to remove sorting of the filenames in CSV altogether. Please let me know if any further changes are required.

**Pull request merged**
