### PR TITLE
update the show function so that you view all frames if the .dcm image has more than 1 frame per file

### PR DESCRIPTION
**Pull request by asvcode**
Most .dcm datasets have 1 frame per file but some datasets have more than 1 frame per .dcm file. In this case the show function fails with a type error.  This update allows the show function to check for the number of ndims and specify how many frames to view (default being set at 1).

### CODE REVIEW

**Comment by jph00** [comment]
Thanks for this. Note that this isn't exported, so it's not actually usable. Add `#export` to the top of the cell, then run `nbdev_build_lib` before you commit. Also, add some markdown prose to explain what this is (since that'll end up in the docs).

**Review by mhh73244 — APPROVED** [review]

**Comment by asvcode** [comment]
Hi Jeremy, I updated the notebook and added #export to the cell and added a short markdown.  Hope this is acceptable now.

**Comment by hamelsmu** [comment]
@asvcode you have to resolve conflicts

**Comment by asvcode** [comment]
Thanks @hamelsmu, I've tried numerous things to try to resolve the conflicts and I just cannot seem to get them to work.  I made the error of including docs in the commit and I have tried to revert the commit `git revert bf78838` and I get the following error:

```
error: could not revert bf78838... added export
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
```

I then tried `git rm docs ` and that messed up the notebook so I had to re-do it.  The docs files requires write access so I have been trying to just remove this file from the commit but so far have been unable to.

Would appreciate any help on this.  Thanks

**Comment by hamelsmu** [comment]
@asvcode 

1. copy your notebook somewhere
2. clone this repo fresh
3. copy your notebook back
4. run the notebook, clean it etc. 
5. open a PR

**Comment by asvcode** [comment]
Got it ! Closing this and will submit a new PR. Thanks

**Pull request closed without merging**
