### PR TITLE
Add support for BFloat16 Mixed Precision

### PR DESCRIPTION
**Pull request by warner-benjamin**
This PR adds support for BFloat16 Automatic Mixed Precision training to `MixedPrecision` and `ChannelsLast`.

To use BF16 AMP, pass `amp_mode=AMPMode.BF16` or `amp_mode='bf16'` to `MixedPrecision`, or use the `Learner.to_bf16` convenience method.

Channels Last training also supports BF16 AMP by passing `amp_mode=AMPMode.BF16` or `amp_mode='bf16'` to `Learner.to_channels_last`.

### CODE REVIEW

**Comment by warner-benjamin** [comment]
#3928 resolves the unrelated CI error.

**Review by jph00 — CHANGES_REQUESTED** [review]
This all looks great, but could you please revert the formatting changes which are using extra vertical space?

**Comment by warner-benjamin** [comment]
Done. I copied from fastxtend and wasn't thinking about formatting

**Comment by jph00** [comment]
Many thanks!

**Pull request merged**
