### PR TITLE
Refactor/add GradCAM functionality

### PR DESCRIPTION
**Pull request by tmabraham**
This adds a separate GradCAM function under the ClassificationInterpretation class. The `plot_top_losses` function has been rewritten to utilize this new function.

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks! Why did you remove the ReLU in `mult`?

**Comment by tmabraham** [comment]
Sorry about that! I was experimenting in my notebook, and when I copied and pasted the code from the notebook, I accidentally left that in. It should be fixed now.

**Comment by sgugger** [comment]
Thanks!

**Comment by dhth** [comment]
This is super useful, @tmabraham. Thanks a lot!

**Pull request merged**
