### PR TITLE
Fix broken links in README and in CONTRIBUTING

### LINKED ISSUE #2652: Readme links return 404 and need to be updated
Links from the [readme](https://github.com/fastai/fastai/blob/master/README.md) which are 404:
* https://github.com/fastai/fastai/blob/master/quick_start
* https://github.com/fastai/fastai/blob/master/tutorial
* https://github.com/fastai/fastai/blob/master/migrating_pytorch (under `Plain PyTorch`)
* https://github.com/fastai/fastai/blob/master/migrating_ignite (under `Ignite`)
* https://github.com/fastai/fastai/blob/master/migrating_lightning (under `Lightning`)
* https://github.com/fastai/fastai/blob/master/migrating_catalys (under `Catalyste`)

### PR DESCRIPTION
**Pull request by hamelsmu**
closes #2652 

@jph00 ready for review

### CODE REVIEW

**Comment by jph00** [comment]
Thanks Hamel! Do you think it's better to fix it this way, or should we fix nbdev to generate the links correctly in the readme?

**Comment by hamelsmu** [comment]
I guess we should fix nbdev?  At least that sounds like the right answer

**Comment by jph00** [comment]
OK - can you add an issue please?

**Comment by hamelsmu** [comment]
closing this PR in favor of #2652

**Pull request closed without merging**
