### PR TITLE
Added docs for WeightedDL

### PR DESCRIPTION
**Pull request by kwsp**
WeightedDL's `wgts` parameter takes an array of weights of the same length as the training data (excluding validation data). This was previously undocumented and caused a lot of confusion for me.

### CODE REVIEW

**Comment by jph00** [comment]
@kwsp sorry it has taken me a while to get to this.

Could you please add the `ImageBlock` import to a non-exported cell? Otherwise it become part of the exported lib, resulting in circular references.

Also, would you be able to add a bit of Markdown prose explaining the code you added?

**Comment by kwsp** [comment]
@jph00 fixed both

**Comment by jph00** [comment]
@kwsp looks like you didn't merge in the changes of today's merged PRs so they're appearing as commits here too.

**Comment by kwsp** [comment]
@jph00 I tried to rebase the new commits earlier and I guess GH created a merge commit. I've removed those.

**Comment by jph00** [comment]
Many thanks!

**Pull request merged**
