### PR TITLE
Fix nested tensors predictions compatibility with fp16

### PR DESCRIPTION
**Pull request by tcapelle**
Modifies retrieving first tensor to check float16 dtype to support nested tensors.
> Warning: This PR needs the flatten function that is added in this other [PR](https://github.com/fastai/fastcore/pull/375).

### CODE REVIEW

**Comment by jph00** [comment]
@tcapelle can you please try changing `listify(flatten(...))` to `concat(...)`, since that's the same thing now

**Comment by tcapelle** [comment]
we have a conflict with `torch_core.concat`

**Comment by jph00** [comment]
OK happy to leave it as-is then. Well spotted on the `concat` name clash - that's actually been there for ages but no-one had noticed before!

**Comment by jph00** [comment]
Just another thought: what if instead of `listify(flatten(self.pred))[0]` we did `next(flatten(self.pred))` ? That would avoid needlessly allocating extra memory.

**Comment by jph00** [comment]
Looks like it's all sorted! I'll update the fastcore version dep too.

**Pull request merged**
