### PR TITLE
Updated Mish to Torch 1.9

### PR DESCRIPTION
**Pull request by digantamisra98**
Fixes [3403](https://github.com/fastai/fastai/issues/3403)

### CODE REVIEW

**Comment by jph00** [comment]
@digantamisra98 looks like you may need to update your version of nbdev and rebuild

**Comment by digantamisra98** [comment]
@jph00 did a pip upgrade and shows that I'm on the latest version. Should I build from source?

**Comment by jph00** [comment]
> @jph00 <https://github.com/jph00> did a pip upgrade and shows that I'm on the latest version. Should I build from source?
> 

That shouldn't be needed. I think somehow you have 2 versions installed or something. Or maybe you've got multiple environments.

I just released a new version which you could try, but the difference you're seeing is from code that was removed many months ago.

**Comment by digantamisra98** [comment]
@jph00 Installed the latest NBDev and did a rebuild. Hopefully this is good now.

**Comment by jph00** [comment]
Oh I think I know what's happening. Your notebooks have `nbdev_comment` lines added. Perhaps at some point you did `nbdev_update_lib` on all the nbs, with an old version of nbdev, so now all your NBs have been changed.

Would you prefer I just made the change manually on my end? Otherwise, might be easiest for you to just delete your local fastai folder and then make the change in the NB and build the lib.

**Comment by digantamisra98** [comment]
Oh okay, sure, if that's convenient for you then that would be great, otherwise I'm happy to follow your recommended steps.

**Comment by jph00** [comment]
Ouch that sure didn't work! I'll do it over here - thanks :)

**Comment by digantamisra98** [comment]
Thanks!

**Comment by jph00** [comment]
I've just pushed that change - please test it when you have a moment.

**Comment by digantamisra98** [comment]
Looks good to me, thanks!

**Pull request closed without merging**
