### PR TITLE
Add built-in integration to Comet

### PR DESCRIPTION
**Pull request by rgaiacs**
Fastai has built-in integration with Neptune, see https://docs.fast.ai/callback.neptune.html.

I use [Comet.ml](https://www.comet.ml/) instead of Netpune and I want to have Comet available from Fastai similar to Neptune.

Is this contribution welcome?

### CODE REVIEW

**Comment by jph00** [comment]
Yes very welcome!

You'll need to `nbdev_build_lib` and also add it to `sidebar.json`.

**Comment by rgaiacs** [comment]
Done.

- [X] run `nbdev_build_lib`
- [X] add it to sidebar.json

**Comment by jph00** [comment]
There's a CI failure -- that's because you need to add all required libs for running the notebooks to the dev requirements in `settings.ini`. Could you do that please?

**Comment by rgaiacs** [comment]
> you need to add all required libs for running the notebooks to the dev requirements in `settings.ini`

Done. :-D

**Comment by jph00** [comment]
Great job!

**Pull request merged**
