### PR TITLE
add documentation for lr_find()

### PR DESCRIPTION
**Pull request by ohmeow**

### CODE REVIEW

**Comment by yanneta** [comment]
ohmeow,
Thanks for helping with this. Note that lr_find can also take a list of learning rates. Could you please document that as well.
Thanks,
Yannet

**Comment by ohmeow** [comment]
Sure.  Just to make sure I'm clear on this ... 

If a list is passed in, it will apply the learning rates to learner's respective groups?  learn.sched.plot() will display the results for the LAST learning rate in the list?

**Comment by yanneta** [comment]
Yes.

**Comment by ohmeow** [comment]
Lmk if that works.

**Pull request merged**
