### PR TITLE
sort Perplexity with NLP metrics

### PR DESCRIPTION
**Pull request by KChalk**
This also puts it immediately adjacent to, but not in, Loss Metrics. Why Perplexity is a subclass of AvgLoss while LossMetric is a subclass of AvgMetric may be worth documenting here. 

Apologies if you think this is trivial, but I almost missed it, as I was not looking for classification metrics.

### CODE REVIEW

**Comment by jph00** [comment]
Many thanks @KChalk ! Could you please run `make` or `nbdev_build_lib` so that the code is synced with the notebooks?

**Comment by KChalk** [comment]
Hi @jph00, I hoped to get around the complex notebook set up by editing the html directly, but I see that I did not manage that. If it's quick for you, I don't need credit for the PR and you're welcome to reject it and redo. Otherwise, I can plan to set up an environment and follow the prescribed steps to make the same change in the not-so-distant future.

**Comment by jph00** [comment]
No worries @KChalk - thanks for letting us know.

**Comment by hamelsmu** [comment]
Thanks, @KChalk looks great 👍🏽

**Pull request merged**
