### PR TITLE
Fix/new tensor for dropout

### PR DESCRIPTION
**Pull request by pford221**
Hello,

This is a very simple PR related to [#2926](https://github.com/fastai/fastai/issues/2926). Please let me know if you have concerns.

Thanks!

### CODE REVIEW

**Review by jph00 — CHANGES_REQUESTED** [review]
Thanks @pford221 ! I think actually `new_empty` would be better. Would you mind making that change?

**Comment by pford221** [comment]
Hi Jeremy,

I'm afraid that this incompatibility is more pervasive than just this instance (I was afraid of that!). Another case is in line 172 of fastai.text.learner in the `LMLearner.predict()` method. Again, calling `idxs.new([idx])` is returning an empty TensorText. 

I'm happy to do what I can to try to spot other instances with a broad find and replace but I worry that I won't always know when the tensor is `TensorText` and whether this issue extends to other sublasses of `torch.Tensor`.

**Comment by jph00** [comment]
My bad - I actually knew about this issue already, but forgot to rigorously check for it. It's actually a change in the PyTorch behavior of `Tensor.new`. We need to replace *all* uses of `new` with `new_empty` for any kind of tensor.

I'll work on fixing this myself tomorrow, time permitting - although a PR in the meantime if you happen to have the time and inclination would be most welcome.

It also sounds like we're missing tests to cover some functionality, since we clearly have bugs which aren't being picked up by tests! :(

**Comment by pford221** [comment]
I tried to update line 172 of fastai.text.learner in the LMLearner.predict() method to:
```
idxs.new_empty([idx])
```
And it threw a CUDA error, "device-side assert triggered". So then I tried to make sure this tensor is on the same device as `idxs` and changed it to:
```
idxs.new_empty([idxs], device=idxs_all.device)
```
Unfortunately that didn't work either.

My point is that it appears - at least in select cases - that simply updating  `new` to `new_empty` might lead to other downstream issues.

**Comment by jph00** [comment]
Yeah sorry what I said was wrong - anyhoo I've patched the PyTorch bug now so `new` works again :)

**Pull request merged**
