### PR TITLE
fix off by one

### PR DESCRIPTION
**Pull request by dreamflasher**
Follow up to this PR: https://github.com/fastai/fastai/pull/3129
Fixes: https://github.com/fastai/fastai/issues/3066

cc @borisdayma

### CODE REVIEW

**Comment by borisdayma** [comment]
@jph00 this looks good to me!

**Comment by jph00** [comment]
Thanks!

**Comment by dreamflasher** [comment]
Thank you all!

**Comment by dreamflasher** [comment]
@jph00 would you be so kind as to release a new version? Would be super helpful for us, because we're depending on the above changes :) Thanks a lot!

**Comment by jph00** [comment]
Sure releasing now.

**Comment by dreamflasher** [comment]
Thank you! You're the best!

**Pull request merged**
