### PR TITLE
Fix tensor->np conversion in old/fastai/model

### LINKED ISSUE #803: ConvLearner fit function does not work
Hi,

I am following lesson 1 of the DLC course and have encountered what appears to be a bug in FastAI itself. The following lines run the training, but fail after for something related to numpy:
```
arch=resnet34
data = ImageClassifierData.from_paths(PATH, bs=8, tfms=tfms_from_model(arch, sz))
learn = ConvLearner.pretrained(arch, data, precompute=True)
learn.fit(0.01, 2)
```
Batch size is 8 because I have only 2GB on my GPU. The error is below:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-11-676345a6c308> in <module>()
      2 data = ImageClassifierData.from_paths(PATH, bs=8, tfms=tfms_from_model(arch, sz))
      3 learn = ConvLearner.pretrained(arch, data, precompute=True)
----> 4 learn.fit(0.01, 2)

~/fastai/fastai/learner.py in fit(self, lrs, n_cycle, wds, **kwargs)
    300         self.sched = None
    301         layer_opt = self.get_layer_opt(lrs, wds)
--> 302         return self.fit_gen(self.model, self.data, layer_opt, n_cycle, **kwargs)
    303 
    304     def warm_up(self, lr, wds=None):

~/fastai/fastai/learner.py in fit_gen(self, model, data, layer_opt, n_cycle, cycle_len, cycle_mult, cycle_save_name, best_save_name, use_clr, use_clr_beta, metrics, callbacks, use_wd_sched, norm_wds, wds_sched_mult, use_swa, swa_start, swa_eval_freq, **kwargs)
    247             metrics=metrics, callbacks=callbacks, reg_fn=self.reg_fn, clip=self.clip, fp16=self.fp16,
    248             swa_model=self.swa_model if use_swa else None, swa_start=swa_start,
--> 249             swa_eval_freq=swa_eval_freq, **kwargs)
    250 
    251     def get_layer_groups(self): return self.models.get_layer_groups()

~/fastai/fastai/model.py in fit(model, data, n_epochs, opt, crit, metrics, callbacks, stepper, swa_model, swa_start, swa_eval_freq, visualize, **kwargs)
    160 
    161         if not all_val:
--> 162             vals = validate(model_stepper, cur_data.val_dl, metrics, epoch, seq_first=seq_first, validate_skip = validate_skip)
    163             stop=False
    164             for cb in callbacks: stop = stop or cb.on_epoch_end(vals)

~/fastai/fastai/model.py in validate(stepper, dl, metrics, epoch, seq_first, validate_skip)
    240             loss.append(to_np(l))
    241             res.append([f(datafy(preds), datafy(y)) for f in metrics])
--> 242     return [np.average(loss, 0, weights=batch_cnts)] + list(np.average(np.stack(res), 0, weights=batch_cnts))
    243 
    244 def get_prediction(x):

~/anaconda3/envs/fastai/lib/python3.6/site-packages/numpy/lib/function_base.py in average(a, axis, weights, returned)
    381             wgt = wgt.swapaxes(-1, axis)
    382 
--> 383         scl = wgt.sum(axis=axis, dtype=result_dtype)
    384         if np.any(scl == 0.0):
    385             raise ZeroDivisionError(

~/anaconda3/envs/fastai/lib/python3.6/site-packages/numpy/core/_methods.py in _sum(a, axis, dtype, out, keepdims, initial)
     34 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
     35          initial=_NoValue):
---> 36     return umr_sum(a, axis, dtype, out, keepdims, initial)
     37 
     38 def _prod(a, axis=None, dtype=None, out=None, keepdims=False,

TypeError: No loop matching the specified signature and casting
was found for ufunc add
```

This looks like something internal to FastAI and its interactions with Numpy. Any help would be greatly appreciated!

### PR DESCRIPTION
**Pull request by ncihnegn**
Fix #803

### CODE REVIEW

**Comment by ncihnegn** [comment]
I can't continue to contribute if you don't even keep my name in the commit.

**Comment by stas00** [comment]
@ncihnegn, your name is on it: https://github.com/fastai/fastai/commits?author=ncihnegn

it's just the way github does/shows PR merges - it shows a merge commit by the person who merged, and yet another commit with the original contribution.

**Comment by ncihnegn** [comment]
Alright, my bad. Somehow didn't see it. I still prefer the "authored by .. and committed by .." way of merging.

**Comment by stas00** [comment]
Please suggest this idea to the github support. When we merge through github we only can press the [merge] button, there are no other options. See [Contact GitHub] link at the bottom of this page.

**Comment by ncihnegn** [comment]
I think it is well supported in github. See this screenshot.
screen shot 2018-10-09 at 2 27 02 pm

**Comment by stas00** [comment]
It's not core github, it's some kind of facebook bot pytorch is using. Can you help us find out how we go about doing the same? We sure thing would like to give as much fame as possible to the contributors.

I only found this https://github.com/facebook-github-bot, but it's a username. It appears to be some facebook internal thing as I can tell from https://hhvm.com/blog/5399/faster-github-commits. I can't find anything that is available outside of facebook.

Let us know what you find and let's take it from there. Thank you for investigating this.

**Comment by ncihnegn** [comment]
Github button has three merging options: create a merging commit, squash and merge, rebase and merge. I think the rebasing merge will work as I expect. You may want to check if rebasing merge is enabled for the repo.

**Comment by stas00** [comment]
Now I lost you, @ncihnegn. Your name already appears on the commit you contributed via PR. I'm not sure how the choice of the merge style will make any difference. It will still say [the same](https://github.com/fastai/fastai/pull/861#issuecomment-428031778).

Can you show us another project where you contributed a PR and it appears there any different than your commit here? Other than facebook-owned projects, which use facebook-github-bot, to which we don't have access to. Once I have a reference point, it's easy to evaluate how to get there. At this moment I no longer understand your needs so that we could meet them.

**Comment by aimran** [comment]
Ultimately its a choice for devs+community but I can confirm that using _either_ the `Squash & merge` or  `Rebase and merge` gives you that "X authored and Y committed" message where X is the original PR author and Y is the committer (typically bot/admin etc)

But the extra merge buttons have to be enabled first.

E.g, https://blog.github.com/2016-09-26-rebase-and-merge-pull-requests/

**Comment by stas00** [comment]
Thank you for clarifying the difference, @aimran. Basically the other two options replace 1+ contributor commits + 1 merge commit with a single commit, which happens to result in a slightly different message in github logs (and makes no difference what-so-ever on git-level).

I still fail to see the practical difference between:

```
commit message...
ncihnegn committed ...
```

and:

```
commit message...
ncihnegn authored ...
```

can you enlighten me of how these two are different? surely 'committed' == 'authored' in any developer's mind, otherwise any commits I make of my own direct contributions (not PR) and which say 'committed' don't mean that I authored them?

Please bear with me, as I'm new to the github culture, do you feel that you're short-changed when the merge style is used instead of the other two? do you get less brownie points this way? And I'm not being sarcastic, just trying to find a way to give the contributors as much fame as it's possible w/o hampering the workflow.

I have a feeling that this is just a matter of preference, since the contributors always get the full credit due either way.

**Comment by ncihnegn** [comment]
I agree there is nothing substantial. Two commits vs one, that is it.

I was mistaken at the beginning.
As I said, I mentioned this merging style just as my personal preference.
Then the thread is extended around how to enable such a style and the benefits.
Definitely not my intention to waste anyone's time.
Thank you for your patience.

**Comment by stas00** [comment]
I personally learned a few things from it (that other projects use a different style), so all is good. I'm glad this has come to a satisfactory resolution. Some of the developers may experiment with these other two styles and perhaps they will become more favorable for them. Let's see. I appreciate the inquisition, @ncihnegn, and am looking forward to more contributions ;)

**Pull request merged**
