### PR TITLE
Improve log_ploss

### PR DESCRIPTION
**Pull request by turbotimon**
Discussion:
https://forums.fast.ai/t/improving-plots-especially-plot-loss/108310

Issue:
https://github.com/fastai/fastai/issues/3963

### CODE REVIEW

**Comment by jph00** [comment]
Many thanks! This is an nbdev project, so the changes need to be made in the source notebooks, and synced from there.

**Comment by turbotimon** [comment]
> Many thanks! This is an nbdev project, so the changes need to be made in the source notebooks, and synced from there.

Thanks for pointing that out and I'm sorry I wasn't aware of it (it's my first post on fastai). I have moved it and hope everything is ok now. If not, please let me know

**Comment by jph00** [comment]
No apologies required! Thanks for putting it in the notebook. So now you need to run `nbdev_export` to sync your notebook with the library.

**Comment by turbotimon** [comment]
Thanks Jeremy (I should have read the CONTRIBUTION.md first)! I now executed `nbdev_export` (`_modidx.py` and `metrics.py` have changed as well as a consequence) and pushed again . What i still don't get, do I have to execute the `13a_learner.ipynb` notebooks as well in order to update the [`### Plotting tools`](https://docs.fast.ai/learner.html#recorder.plot_loss) section or is this done by the ci/cd pipline?

**Comment by jph00** [comment]
> Thanks Jeremy (I should have read the CONTRIBUTION.md first)! I now executed `nbdev_export` (`_modidx.py` and `metrics.py` have changed as well as a consequence) and pushed again . What i still don't get, do I have to execute the `13a_learner.ipynb` notebooks as well in order to update the [`### Plotting tools`](https://docs.fast.ai/learner.html#recorder.plot_loss) section or is this done by the ci/cd pipline?

The docs are updated automatically for showing function signatures. The rest of the notebook is simply rendered as-is -- so if you have any new cell outputs, they will appear in the docs too.

**Comment by jph00** [comment]
That's odd - CI is being rather fussy, and complaining that your modidx file has a difference in line endings. Perhaps you modified it manually after syncing?

**Comment by turbotimon** [comment]
> That's odd - CI is being rather fussy, and complaining that your modidx file has a difference in line endings. Perhaps you modified it manually after syncing?

I saw that too. However, I didn't touched it and when I git-reset `_modidx.py` and run `nbdev_export`, eol is missing again (also on clean `upstream/master`), can you reproduce that? I'm using Codespace, so it shouldn't be a problem with my machine too

**Comment by turbotimon** [comment]
I merged the current master, but the problem with `_modidx.py` didn`t change, so I reset it manually. I hope it is ok not to merge

**Comment by turbotimon** [comment]
@jph00 Hi Jeremy, just wondering if this could be merged or if you need something else? Let me know if somethings missing!

**Pull request merged**
