### PR TITLE
Update core docs

### PR DESCRIPTION
**Pull request by bfarzin**
Update of `core docs` example page

### CODE REVIEW

**Comment by stas00** [comment]
The numpy issue (https://github.com/fastai/fastai/pull/1448#issuecomment-453265239) is still there, please have a look at the diff.   

which of these 2 generates this?
```
from fastai.gen_doc.nbdoc import *
from fastai.core import *
```

and perhaps go into the imports and try to reduce it to the small code sample that reproduces the problem?

And until then perhaps manually remove that error cell via editor, so that your PR could be merged and we can continue sorting out the numpy issue in parallel. Probably again take it to the forums dev chat probably would fit the best: https://forums.fast.ai/t/developer-chat/22363/625

**Comment by bfarzin** [comment]
I no longer see this problem on my local version.  All tests pass for me in the `docs_src` and the `make test`
Are you testing on your local system?  Could it be that you have a Numpy difference/conflict there?
How can I replicate the error you are seeing? (I will post on the dev forum also, hoping to get some more input)

**Comment by sgugger** [comment]
Thanks. Why are you using help? The documentation of the functions is shown with the command `show_doc(func_name)` in a hidden cell. I'd remove the three corresponding cells.
All the examples seem pretty good, otherwise.

**Comment by stas00** [comment]
> I no longer see this problem on my local version. All tests pass for me in the `docs_src` and the `make test`
> Are you testing on your local system? Could it be that you have a Numpy difference/conflict there?
> How can I replicate the error you are seeing? (I will post on the dev forum also, hoping to get some more input)

It's not on my system, but yours: It's in your commit, see:
https://github.com/fastai/fastai/pull/1457/commits/7b1a79665d05655ddc66f2013ef3d42bf2695d39

**Comment by bfarzin** [comment]
@sgugger I thought it would be helpful to see the function signature right there; I now see how that could be confusing.
@stas00 Thank you for pointing out the error that is on my side.  I will post in the forum on how this occured.  I have fixed and will re-submit PR  Thank you so much for your patience and help with resolving this!  I learned a lot and will not make this error again.

**Pull request closed without merging**
