### PR TITLE
Updates image scaler to be more efficient

### PR DESCRIPTION
**Pull request by karanchahal**
Uses a better mechanism to change scale of image if it's expanding. CV_INTER_LINEAR  is a better choice than CV_INTER_AREA for expanding an image. CV_INTER_AREA is better for shrinking an image.

References #618

### CODE REVIEW

**Comment by karanchahal** [comment]
@sgugger @jph00  Any updates on the review for this ?

**Comment by sgugger** [comment]
Sorry, I thought I left a comment a few days ago, but I forgot to press the last button. There is a little bug I think.

**Comment by karanchahal** [comment]
Yes, you are right, So sorry for this bug. I have corrected and pushed the code with the correct variable name.

**Comment by karanchahal** [comment]
Cheers ! Is there anything else you would like someone to take a look at? I'm going through the fast.ai codebase as it is. Would be happy to submit a PR for some fixes.

**Comment by sgugger** [comment]
We're in the process of rewriting the version 1 of this library, so in the meantime we only maintain this one with minor fixes. Stay tuned for the new version in October!

**Pull request closed without merging**
