### PR TITLE
Tests for vision.gan

### PR DESCRIPTION
**Pull request by ericricky**
This is my first attempt at a test script for vision.gan. Before I go any further, I was hoping to get some feedback. Can the tests that I've written so far be improved? My test for GANTrainer takes much longer than the other tests at around 6 seconds. Is there a guideline for how long the entire script should take? I've been taking inspiration from a few different test modules. Is there any one in particular that I should look at to use as a model? Also, I've noticed that there are some implicit requirements on the shapes of images and possibly other parameters. Image sizes seem to need to be powers of 2. Is that expected?

### CODE REVIEW

**Comment by sgugger** [comment]
This is looking good, thanks a lot! One thing is that we can't have a training without marking it with `@pytest.mark.slow` as we want the suite to run fast most of the times. Can you just add that decorator to the slow test?

**Comment by ericricky** [comment]
@sgugger Yeah I'll do that. Also, should I include the update to the test registry in my pull?

**Comment by sgugger** [comment]
Yes please, it's better this way.

**Comment by ericricky** [comment]
Actually, how do I run a test marked with slow? I tried `pytest -m slow tests/test_vision_gan.py` but it still skipped.

**Comment by sgugger** [comment]
pytest --runslow

**Comment by ericricky** [comment]
@sgugger Awesome, thanks. I'll try to add a few more tests in the next few days, but feel free to merge if it looks good to you.

**Comment by sgugger** [comment]
Let's do small increments! Thanks for this!

**Comment by ericricky** [comment]
No problem, and sounds good!

**Pull request merged**
