### PR TITLE
Improvedoctest

### PR DESCRIPTION
**Pull request by Benudek**

### CODE REVIEW

**Comment by Benudek** [comment]
context: 
https://forums.fast.ai/t/doc-test-project/38344/155?u=benudek
https://forums.fast.ai/t/doc-test-project/38344/154?u=benudek

**Comment by stas00** [comment]
I haven't tried running it yet, but looking at the code - looks excellent, @Benudek.

I'd ask to only change:
```
  apiTestsMap = dict()
    oneOrMoreTestsfailed = False
```
we don't use CamelCase other than for class names.

So apiTestsMap => api_tests_map
oneOrMoreTestsfailed => some_tests_failed (some = one or more)

and later once it's all happy and working, we would need to go over and use consistent naming for the map/db/file, as now it's a bit all over. But will worry about it later.

So please make these 2 case renames and this is good to good.

Thank you.

**Comment by stas00** [comment]
And looking again why `RegisterTestsPerAPI.oneOrMoreTestsfailed`, when it can just be a local variable in `conftest.py`?

**Comment by Benudek** [comment]
think RegisterTestsPerAPI.some_tests_failed could go to conftest - but needs to be a class var, since is called on every test.

I am actually fine to go through these little improvements like naming conventions, if we make a list.

Some small things I saw (and we can extend the list and I can correct)
-  I use inspect.currentframe while I seem to remember we want to just say currentframe and import inspect accordingly
- in this I use fastaimodule = re.match(r'^fastai\..*',fq_apiname) to exclude non fastai APIs that were registered. Since we really do not want that in the code, could in full_name_with_qualname just raise an exception if that match isnt given. So, we force developers to revisit their code.

**Comment by stas00** [comment]
Ah, ok, I couldn't tell from looking at the diff. Will look closer once it's in. 

Let's do just FooBar to foo_bar, commit and then deal with the finetuning later.

**Pull request closed without merging**
