### PR TITLE
Fix filter_by_folder

### PR DESCRIPTION
**Pull request by odysseus0**
Please refer to the notebook below for more details:

https://nbviewer.jupyter.org/gist/odysseus0/d7b10d1f0e226d74ff05f2cd6fdb5e00

### CODE REVIEW

**Comment by sgugger** [comment]
Oh yes, this doesn't work properly in this instance, thanks for flagging.
The problem with converting everything to a Path object is that it can be very slow (for datasets like imagenet for instance), so we would need a speed check, and if this doesn't pass it, we will need another way of fixing the problem.

**Comment by odysseus0** [comment]
Sign. I guess that most convenience comes with a performance overhead. `pathlib` is so much nicer to use compared to `os`.

**Comment by odysseus0** [comment]
I guess this is a place where there needs to be a consensus, about where we should continue to use `pathlib` for the path handling, or even whether we should continue at all if the performance overhead is indeed so bad. Enforcing an agreed upon way of doing things, at least internally inside the library, will help us avoid bugs like above.

**Comment by sgugger** [comment]
I've just pushed another way to fix. Note that it won't work with your example of '3', it filters the base folders only.

**Pull request closed without merging**
