### PR TITLE
Enhancement: Let TextDataLoaders take in a custom tok_text_col

### PR DESCRIPTION
**Pull request by muellerzr**
Fixes bug introduced in https://github.com/fastai/fastai/pull/3204 and properly implements wanted feature

### CODE REVIEW

**Review by jph00 — CHANGES_REQUESTED** [review]
Thanks for this. Can you please add a little documentation and a test?

**Comment by jph00** [comment]
Sorry @muellerzr looks like a conflict has appeared - any chance you could resolve that so I can merge this?

**Comment by muellerzr** [comment]
Sure. Will also add a brief test as well

**Comment by muellerzr** [comment]
@jph00 made adjustments. The test will fail based on the previous commit we're fixing (since IMDB_Sample names it's text column as `text`, it's an easy situation to miss)

**Comment by jph00** [comment]
Great!

**Pull request merged**
