### PR TITLE
Add Dynamic Loss Scaling to MixedPrecision Callback

### PR DESCRIPTION
**Pull request by flpeters**
New Feature: Dynamic Loss Scaling when training in `fp16` (Mixed Precision).

Every `max_noskip` steps `loss_scale` is doubled, until it has reached `max_loss_scale`. If at any point during training, after the backward pass, any gradient is `inf`, `-inf` or `nan`, the weight update will be skipped and `loss_scale` is halved.
This prevents a model from being destroyed (the parameters turning `nan`), because updates that would cause this are never performed.
The code is heavily inspired by [NVIDIA amp](https://github.com/NVIDIA/apex/tree/master/apex/amp) which is licensed under the [BSD 3-Caluse License](https://github.com/NVIDIA/apex/blob/master/LICENSE). I did write everything myself, meaning no line of code was copied, but the idea on how to do it is entirely theirs.
Testing this feature can be done by training a model in fp16 and setting `max_noskip` to something low like 20. That way `loss_scale` will increase every 20 steps until the gradients overflow, at which point an update is skipped and `loss_scale` is reduced again.
I haven't changed [this line](https://github.com/fastai/fastai/blob/b935a205758456d3b1f0a665ba118b9d150614e6/fastai/train.py#L37) yet, because there are probably more intuitive names for the arguments than what I came up with.

Using this I was able to successfully train a model whose parameters had previously always turned `nan` at some point. 
capture

Todo:
- Add the new arguments to `to_fp16`
- If there are any other sources where the loss could possibly become `nan`, something where decreasing `loss_scale` doesn't help, then it will get stuck trying to decrease `loss_scale` as much as possible. A fix would be to keep track of how many times `loss_scale` was reduces in a row and to throw an error if it exceeds some number.

### CODE REVIEW

**Comment by sgugger** [comment]
It's funny I was working on this specifically just yesterday! This looks great but I have a few things I'd like refactored and I also wanted to start high then diminish instead of rising the loss scale, providing the option to do a fix or dynamic loss scale.
Depending on the time you have to put on this, I can either merge and work from what you've done, or suggest changes in a code review, let me know what you prefer.

**Comment by flpeters** [comment]
Thank you for your feedback! Since you were already working on this, you probably know exactly where to go from here so feel free to continue from where I left of. I'm glad I could be of some help :)

**Comment by sgugger** [comment]
Noted. I'll merge and take over then, thanks a lot!

**Comment by sgugger** [comment]
If you want to have a look at my changes, it's all in [this commit](https://github.com/fastai/fastai/commit/d8cdcc21c4edef9fc6369e232073b6c3ce3051dd).

**Pull request merged**
