### PR TITLE
Rewrite README to be more modular

### PR DESCRIPTION
**Pull request by Eric-Arellano**
Changes:
* Added section headers.
* Clarified Anaconda is a prereq for installing, and linked to install.
* Added instructions for testing.
* Linked to guide for setting up Paperspace.
* Removed outdated `README.rst`.

P.S. Do you know why Travis isn't showing on PRs? I see you have Travis set up, but I think it might not be linked to the GitHub repo properly. 

P.S.S. Thank you for this course! I'm really enjoying it.

### CODE REVIEW

**Comment by jph00** [comment]
Many thanks! I know a kind committer added stuff for Travis, but I suspect I need to do something at my end to actually enable it. I'll look at that now.

**Comment by Eric-Arellano** [comment]
@jph00 Let me know if I can help at all with Travis! For example if you're comfortable giving me the login I'd be happy to set it up - no worries if you're not comfortable with that.

I don't know much DL to help with any of that, but would love to help with the software engineering side of things.

**Comment by jph00** [comment]
Many thanks @Eric-Arellano - I think it should be working now. If you see anything that looks screwy, feel free to open an issue or send in a PR.

**Comment by gsgbills** [comment]
@Eric-Arellano  After the instructions for testing, should there be a link to where/how "report" on test failures?

**Comment by Eric-Arellano** [comment]
Good idea @gsgbills! I'll update that.

**Pull request merged**
