### PR TITLE
Optionally run AWD-LSTM from pre-computed embeddings

### PR DESCRIPTION
**Pull request by herrmann**
This patch allows someone using AWD-LSTM to calculate the forward pass directly from the embedded input. The alternative would be copying-pasting the model and splitting the embedder and encoder, but that would complicate code maintenance and break compatibility with saved models. This is needed in case someone needs to calculate the sequential Jacobian (I'll send another patch for this) or re-use the embeddings somewhere else.

### CODE REVIEW

**Comment by sgugger** [comment]
Mmm, can you try to see if setting 
```
model.encoder_dp = noop
```
doesn't solve your issue? I'd rather not add a layer of complexity to an already fairly complex model.

**Comment by herrmann** [comment]
Not quite... for calculating the intrinsic attention (or input sensitivity, or part of the sequential Jacobian) I need to calculate the partial derivatives of the embedded sentence w.r.t. the particular classification's softmax score. To do that, I embed, detach and set require_grad to True, then forward the model up to classification, call backward() and then proceed calculating the intrinsic attention from the embedding's grad.

Do you think I should I copy this thread in the forums as well? Thanks in advance!

**Comment by sgugger** [comment]
Yes please, I'd like to make sure more people would benefit from this.

**Comment by stas00** [comment]
That doesn't look right. You probably need to rebase your fork.

**Comment by stas00** [comment]
Also: Please sign this CLA agreement https://www.clahub.com/agreements/fastai/fastai as explained [here](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md) before we can proceed.  Thank you.

**Comment by herrmann** [comment]
Oops, I messed up the pull request... I'll open another one with both changes (AWD-LSTM patch and the TextClassificationInterpretation class)

**Comment by herrmann** [comment]
New pull request: https://github.com/fastai/fastai/pull/1688

**Pull request closed without merging**
