### PR TITLE
Bugfix/default drops text learner

### PR DESCRIPTION
**Pull request by bachsh**
When setting more than one hidden layer using `lin_ftrs` in `get_text_classifier` without setting `ps`, a wrong architecture is created. This PR fixes is and also issues an error when trying to init the internal `PoolingLinearClassifier` improperly.

### CODE REVIEW

**Comment by sgugger** [comment]
It looks like it's breaking existing behavior since the tests aren't passing. Can you check and debug? Thanks!

**Comment by bachsh** [comment]
Sure, I was in a hurry and didn't wait for the tests to finish. The error
says something is wrong with bash, so I can't tell which test failed
exactly. I'll look for them when I get to my computer.

**Comment by sgugger** [comment]
If you click on the line Run tests 1 error, you will see the details.

**Comment by bachsh** [comment]
I made the change and tests in one repo and then copied to the other without testing. What a noob :(

Fixed it now.

**Comment by sgugger** [comment]
Thanks!

**Pull request merged**
