### PR TITLE
fix fastai/fastbook/issues/263

### PR DESCRIPTION
**Pull request by Tagar**
potential fix for fastai/fastbook#263

### CODE REVIEW

**Comment by Tagar** [comment]
Looks like all tests passed except this one - 

Screen Shot 2020-09-13 at 10 58 11 PM

The reason is that I didn't regenerate the callback/schedule.py from notebook, and not sure why that new line is now missing.

**Comment by Tagar** [comment]
I tested locally with fastai installed from this branch (https://github.com/fastai/fastbook/issues/263) 
`pip install git+git://github.com/Tagar/fastai.git`

and it solves the [issue]

**Comment by Tagar** [comment]
All tests pass now too.

**Comment by jph00** [comment]
Many thanks!

**Pull request merged**
