### PR TITLE
Add TabWeightedDL class

### PR DESCRIPTION
**Pull request by myenugula**
Add a new feature to fastai; Tabular Weighted Data Loader (TabWeightedDL class).
This PR solves #3860. Please check my comment on the issue

### CODE REVIEW

**Comment by avatarfeb26** [comment]
Hi @jph00
Could you please review this PR? Thanks

**Comment by myenugula** [comment]
Hi @jph00
Could you please review this PR? Thanks

**Comment by jph00** [comment]
Looks good, except there's an extra nb change which changes the path - could you remove that please?

**Comment by myenugula** [comment]
Thank you Jeremy! I missed that one and committed it accidentally.
I fixed sync and merge conflicts.

**Comment by jph00** [comment]
Many thanks!

**Pull request merged**
