### PR TITLE
Added try except AttributeError

### PR DESCRIPTION
**Pull request by us**
Added to "'NoneType' object has no attribute 'group'" error.

### CODE REVIEW

**Comment by sgugger** [comment]
Good point. Maybe we can use the same assert as [here](https://github.com/fastai/fastai/blob/8a54d18ab21f9f60473a39927dd9c3b3397e8e95/fastai/data_block.py#L268) to make the behavior consistent?

**Comment by us** [comment]
@sgugger thank you  I fixed it.

**Comment by sgugger** [comment]
Thanks!

**Comment by sgugger** [comment]
Oops, I misunderstood what you were trying to achieve. We don't want to go with the error being silent here, since it'll make things fail later on. We want the user to clearly know the pattern wasn't found in res so they can adjust their regex (or use another labelling method, or get rid of the samples that don't work).
I reverted.

**Pull request merged**
