### PR TITLE
Fix casting types for mps

### PR DESCRIPTION
**Pull request by MSciesiek**
Fix for the issue https://github.com/fastai/fastai/issues/3911

### CODE REVIEW

**Comment by jph00** [comment]
Thanks for the contribution! This is an nbdev project, so the actual source is in the notebooks, and the .py files are auto-generated. Could you please make your edit in the notebook too? Also, please add a comment above explaining why the extra casts are there?

**Comment by MSciesiek** [comment]
Sure, I will do a proper local setup and will do then the requested changes. Most probably over the coming weekend.

**Comment by jph00** [comment]
@MSciesiek just following up on this

**Comment by jph00** [comment]
Thank you!

**Pull request merged**
