### PR TITLE
OurDistributedSampler would shuffle for TextClasDataBunch 

### PR DESCRIPTION
**Pull request by philtrade**
Fix for issue #2501.

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks!

**Comment by philtrade** [comment]
Hi Sylvain,

Would it be useful if I port over the recent DDP related changes
(lr_finder, GANTrainer, and this TextClasDataBunch related) from v1 to v2?
I understand V2 has a July deadline, let me know if I can be helpful in
anyway (disclaimer: I'm totally new to nbdev, the code-walkthroughs, and v2
in general).

Thanks.

**Comment by philtrade** [comment]
Last comment deleted: I realize it's not useful until I'm warmed up to v2 and ready to contribute.

**Comment by sgugger** [comment]
Please take your time to learn v2, but every PR is always welcome. Worst case scenario is we ask you to rewrite some bits of it if they don't go well with the rest of the code, and we don't bite ;)

**Pull request merged**
