### PR TITLE
Adding splitter kwarg - issue 3367

### PR DESCRIPTION
**Pull request by tgalery**
See https://github.com/fastai/fastai/issues/3367

This would allow for a parent splitter defined in the issue to to split train and validation subfolders (containing text files) from a parent folder . The splitter above could be added as part of this PR if it interests the community

### CODE REVIEW

**Comment by tcapelle** [comment]
why the CI is passing on this, the corresponding `.py` is not in sync.

**Comment by tgalery** [comment]
@tcapelle I didn't know I had to change the corresponding .py file (though these would be auto generated somehow) but happy to push those changes if that's what you need.

**Comment by tcapelle** [comment]
but for instance this: https://github.com/fastai/fastai/pull/3420 fails

**Comment by jph00** [comment]
Apologies @tgalery I hadn't seen this. You need to run `nbdev_build_lib` as discussed in the developers guide: https://docs.fast.ai/dev-setup.html . Many thanks!

**Comment by tgalery** [comment]
cheers, I'm gonna rebase and run this, thanks.

**Comment by tgalery** [comment]
Done @jph00

**Comment by jph00** [comment]
Many thanks!

**Pull request merged**
