### PR TITLE
File tokenizer

### PR DESCRIPTION
**Pull request by bfarzin**
OK, Another attempt at this with feedback form @kliron to help with managing the process across multiple cores.  Writes to temp files and then pulls form those to `Numericalize`

Some issues/questions:
1. Where is the best place to write these temp files?
2. Should we use a memory map to prevent copying the file across processes (I still see a big memory footprint when I run this code.)  My input file is 1.75 GB and I run on 16 cores and my peak memory is about 16 * 1.75 = 28 GB.  That seems high. Any pointers on how to lower that would be very helpful.
3. How/what should be done with the current `Tokenizer`?  Can we replace or should we keep two copies and if two copies any suggestions about naming?

Also, as usual, I appreicate any feedback on coding style or format that makes things easier to understand.  All is a bit messy right now, but if the overall approach looks good, I can clean up and streamline moving some functions into `core`, etc. 

Thank you for reviewing and considering!

### CODE REVIEW

**Comment by sgugger** [comment]
Thank you, Bobak, but as discussed in the [issue](https://github.com/fastai/fastai/issues/1998) I was already planning on resolving it but it can't happen until the course material is merged into master (new fastai code base), so now is a really bad timing to sort the nuances out.

I think you work would be very helpful to me to complete this task, I hope you're OK if we put this on hold and then revisit it once the new code base is created.

Until then @kliron or any person interested could use your branch if need to (it's breaking the test suite though, so at their own risks).

**Comment by bfarzin** [comment]
Totally ok with putting on hold.  Glad that it can be of some help to you when you come back to it (if it is.) 
Great exercise for me to work through the details.  I understand that part of the code much better than I did before.  I believe I can create my own files that reference this and use till you get to it.  

Thanks for having a look.  Let me know if I can help in any way with it when you get around to the details.  Happy to assist!

**Comment by sgugger** [comment]
I will definitely look at your code as I create the new tokenizer and will appropriately cite on the bits I take. I'm leaving this PR open until v1.1.0 is out (at least in a branch state) so anyone can fork your code in the meantime.

**Comment by kliron** [comment]
Regarding your memory concerns, take into consideration that tokenization is a *very* memory intensive operation (as just about anything in NLP is). Spacy is clever in trying to optimize as much as it can by caching all tokens, hashing them and not keeping multiple copies of strings in memory but, again, the limitations of Python's multi-process concurrency model takes its toll as the cache cannot be shared across all tokenizers. 
Even worse, memory that is garbage collected by Python [is not guaranteed to be released back](http://effbot.org/pyfaq/why-doesnt-python-release-the-memory-when-i-delete-a-large-object.htm) to the OS - the only way to have this guarantee is to have the memory intensive operation run in a subprocess and have that terminate immediately after work, which is kinda what we try _not_ to do here.

**Comment by sgugger** [comment]
Closing for the same reasons as the issue. Thanks a lot for the PR as it gave us an example on which we have built. The fork can still be accessible for anyone who wants to use this even if the PR is closed (and you can link on the forum to help people find it @bfarzin).

**Comment by bfarzin** [comment]
Glad that this helped you in some small way!!

**Pull request closed without merging**
