### PR TITLE
Fixed FastAI Docs Typo & Dead Link

### PR DESCRIPTION
**Pull request by JSalenger**
Hi folks,
This is my first PR ever on a public repo, so if there's an error I apologize. 

I didn't do anything too radical, but I fixed a typo on this page [external data](https://docs.fast.ai/data.external.html) and a dead link on this one [fp16 callbacks](https://docs.fast.ai/callback.fp16.html). I didn't run any cells so I don't think that I have to run nbdev install git hooks, but if that's incorrect I can do so. 

The dead link fix closes issue #3191 
The typo hasn't been mentioned in an issue I've found.

Thanks!

### CODE REVIEW

**Comment by JSalenger** [comment]
Ok I was wrong looks like I do, in fact, need to clean the notebooks.

**Comment by jph00** [comment]
Please let me know when it's ready to review, and at-mention me. (It's marked as a draft at the moment)

**Comment by JSalenger** [comment]
@jph00 Hey sorry, I couldn't figure out why the third check was failing. It should be ready now? I couldn't find anything wrong with nb 18.

**Comment by hamelsmu** [comment]
@jph00 I fixed this PR (the notebooks were out of sync with the lib), and I also fixed the CI.  It's ready for review.

**Comment by JSalenger** [comment]
Thank you so much!

**Comment by hamelsmu** [comment]
I can actually merge this.  Thanks,  this I just minor documentation change

**Pull request merged**
