### PR TITLE
extending ImagePoints for more informative visualization

### PR DESCRIPTION
**Pull request by sutt**
[Forum discussion](https://forums.fast.ai/t/extending-imagepoints-for-more-informative-visualization/44431)

This is the initial commit to review core code. Based on feedback I will implement tests and docs, merge formatting to fastai standards, and perform final TODO's annotated in code.

Here's the [demo notebook](https://github.com/sutt/fastai-tmp/blob/master/MultiIP-documentation.ipynb) for the functionality of the new class, `MultiIp`

**Quick Discussion** (deeper discussion in demo notebook)
A useful visualization is critical to debugging ImagePoint tasks: while ImageBBox and ImageSegment objects have advanced .show() methods, ImagePoints does not. Furthermore,  segments / bbox are not appropriate to some types of analysis (e.g. facial points). 
This feature extends the .show() functionality of Image / ImagePoints without interfering with or changing those base classes. It allows concise out-of-the-box visualization between sets of points (model vs ground truth or model1 vs model2) and also allows the user to pass in arbitrary params to matplotlib styling, but apply distinct styles to distinct points.
This has helped my own work when trying to characterize what type of prediction-mistakes are corrected by different training protocols and different models.

I'm open to different naming of this class: perhaps `MultiImagePointsDisplay` or `DistinctImagePointsViz` fits better with fastai naming style?

### CODE REVIEW

**Comment by sgugger** [comment]
It's looking fine to me. I think `DisplayImagePoints` would be a better name since it's mostly about that.
When you refactor, in terms of style, if you could mimic the general style of the library with:
- 1-line docstrings that briefly explain the goal, with args or class/type names between backsticks
- type annotations for your function args
- less vertical space (a lot of blank lines or if statements that could fit on the same line)
that would be great!

**Comment by sutt** [comment]
in progress (4/27)

**Comment by sgugger** [comment]
Hi there, fair warning, we are in the midst of completely rewriting this part of the library for v1.1.0. While we will still accept any PR, maybe it would be best to put your contribution on hold until v1.1 is out (by the end of this month I hope)?

**Comment by sutt** [comment]
Thank you for the warning! I'll hold off.
Is there any discussion on forum etc where I can follow along 1.1 dev
goals, or is it mostly internal?

**Comment by sgugger** [comment]
Internal for now, as we're polishing the roadmap. Once it's ready we'll publish it on the forum (hope by end of week).
Since you're holding off, I'm closing this PR and we can reopen (or start anew) once v1.1 is out and you're ready to tackle this!

**Pull request closed without merging**
