### PR TITLE
Added Darknet

### PR DESCRIPTION
**Pull request by sgugger**

### CODE REVIEW

**Comment by sgugger** [comment]
Hi @apiltamang 
Not sure of the way I'm doing my PR as well, it's very new to me. If you want some sample code, there is
[this notebook](https://github.com/sgugger/Deep-Learning/blob/master/Resnet%2050%20and%20Darknet%2053.ipynb).

**Comment by apiltamang** [comment]
Took a quick swab at your notebook...
The accuracies and the log-loss seem very off (0.0025 now versus >.99% from when I was taking the Part-1 course). Any explanation you could provide for that? Thnx..

**Comment by sgugger** [comment]
Oh, it's not a pretrained model. The steps you can see on the notebook are only the first ones toward real training on the whole ImageNet that Jeremy would like to try.

**Comment by jph00** [comment]
I'd rather use github PR comments for me  to do code reviews and for
authors to reply and ask questions etc - let's use the forums for
discussions please.
--
Jeremy Howard


On Mon, Apr 9, 2018, at 9:43 AM, apiltamang wrote:
> Took a quick swab at your notebook...
>  The accuracies and the log-loss seem very off (0.0025 now versus
>  >.99% from when I was taking the Part-1 course). Any explanation you
>  could provide for that? Thnx..> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/fastai/fastai/pull/328#issuecomment-379817136

**Comment by apiltamang** [comment]
@sgugger Perfect.. thnx for clarifying. @jph00 will do.

**Pull request merged**
