### PR TITLE
Fix Tokenizer.get_lengths

### PR DESCRIPTION
**Pull request by karotchykau**
Fixes [#3666](https://github.com/fastai/fastai/issues/3666).

### CODE REVIEW

**Comment by jph00** [comment]
Many thanks for the PR. Note that fastai is an nbdev project, therefore edits need to be made in the notebooks, not the .py files -- the .py files are auto-generated. A walk-thru is here, if needed: https://docs.fast.ai/dev-setup.html

Also, could you explain more about the reasoning for the first change you made, to reverse the check for `None`?

**Comment by karotchykau** [comment]
> Many thanks for the PR. Note that fastai is an nbdev project, therefore edits need to be made in the notebooks, not the .py files -- the .py files are auto-generated. A walk-thru is here, if needed: https://docs.fast.ai/dev-setup.html

Got it. Only fixed it in `nbs/30_text.core.ipynb`.

> Also, could you explain more about the reasoning for the first change you made, to reverse the check for `None`?

I think we don't need to reverse but the current version is incorrect anyway. Here is what I mean. There are two modes:
* `df`, it will save `text_length` into some DataFrame, however, it doesn't save these lengths into `self.lengths`.
* `folder`, it doesn't have `text_length` at all (and can't have it), however, it saves these lengths into `self.lengths`.

If `if self.lengths is None: return None` comes first, `if self.mode == 'df'` will never be executed because `self.lengths` is always `None` for this mode, these lengths are stored as a column in this DataFrame. Please note that `if self.mode == 'folder'` will work fine.

I see two solutions here:
* Save `self.lengths` for the `df` mode as well. Not great because we basically repeat it two times.
* Put `if self.lengths is None: return None` between `if self.mode == 'df'` and `if self.mode == 'folder'`. In this way, all the conditions above will be satisfied.

Sorry, that was my bad. I didn't check how the `folder` mode behaves. The changes were amended.

**Comment by karotchykau** [comment]
> Save `self.lengths` for the `df` mode as well.

To be honest, this solution can also be applied without any problems. Saving of lengths can be added to `Tokenizer.setups`. When these lengths are saved there, `if self.lengths is None: return None` will not be triggered in `get_lengths` if everything is initialized. Now `Tokenizer` with the `df` mode will have `self.lengths` that is not `None` as before. This solution is more "general" because it allows to call `self.lengths`.

I also encountered a bug when `tok_text_col` is different from the default name in `tokenize_df`. `'text_length'` is specified inside `get_lengths`, therefore, it will not be executed if you provide a different name.

Implemented this "general" solution. It works for every mode now. Please see the latest amended commit.

**Comment by jph00** [comment]
Nice - that's looking much better!

**Pull request merged**
