### PR TITLE
Add documentation for hugging face hub integration

### PR DESCRIPTION
**Pull request by omarespejel**
## What?
Docs for the `from_pretrained_fastai` and `push_to_hub_fastai` functions to share and load models to the Hugging Face Hub, respectively.

The functions can be explored here: [Open In Colab](https://colab.research.google.com/gist/omarespejel/9ba054ce74c7a4d4408085b611124bdf).

## Why?
Together we can advance Open-Source ML 🚀. The Hub aims to build the most extensive collection of Open Source models, datasets, and demos. The "solve AI" problem won't be solved by a single company, but by a culture of sharing knowledge and resources. This is something that fastai has taken to the next level 🌈. 

By sharing Learners to the Hub, fastai users will have their work exposed to over 100,000 users (and quickly growing). 

## How?
An `nbs/74_huggingface.ipynb` notebook was created.
* The auto-generated fastai/huggingface.py is included. If required I can eliminate it.
* Docs include an introduction on WHY fastai users would benefit from sharing their models through the Hub

## Something else?
* Maintainance of the docs and the working of the integration functions are done by the hf team (main contact @espejelomar).

### CODE REVIEW

**Comment by jph00** [comment]
Thanks @omarespejel . A few requests:

- Remember this is fastai docs, not hf docs. Don't use words like "us"
- Remove all marketing-oriented material, such as statistics about HF Hub
- Try to match fastai's prose style. We don't tend to use stuff like emojis. We try to focus on just imparting what the user needs to know
- Move the implementation code into HF's lib, rather than implementing it here. This should just be a tutorial
- Be sure to clean your NBs. `nbdev_install_git_hooks` will do that automatically. https://docs.fast.ai/dev-setup.html
- We're not too fussy about it, but try to follow at least the spirit of our coding style guide: https://docs.fast.ai/dev/style.html

**Comment by omarespejel** [comment]
Thank you for your kind guidance @jph00! I applied it accordingly. Just one question:
- The [fastai/huggingface.py](https://github.com/fastai/fastai/pull/3627/files#diff-5285402466cd6b3095c6e52eb0688f764b9a416c6b838fd2dc75a00c9a1658d8) file, although empty, is still being generated after running [`nbdev_build_lib`](https://nbdev.fast.ai/export2html.html#nbdev_build_lib). Shall I eliminate it?

**Comment by omarespejel** [comment]
Thank you Jeremy! Upgrading `nbdev` worked. Sorry for the earlier mismatch between the writing style of the fastai docs and my first commit. I made strong changes to be consistent with fastai.

**Comment by jph00** [comment]
Many thanks. No need to apologise - that's what PR reviews are for!

**Pull request merged**
