### PR TITLE
fix for pretrained in vision.learner

### PR DESCRIPTION
**Pull request by peterdudfield**
fix for pretrained in vision.learner

Make sure input is ```pretrained=pretrained```

#3745

### CODE REVIEW

**Comment by jph00** [comment]
Thanks @peterdudfield . This is an nbdev project so fixes need to be made in notebooks and then the lib built from there. I'll fix it at our end to save you the trouble.

**Comment by peterdudfield** [comment]
Thanks @jph00 , please let me know the commit, I would be interested to see how it is done

**Comment by peterdudfield** [comment]
I think ive done it [here](https://github.com/peterdudfield/fastai/blob/bug/3745-unet-xse_resnext50/nbs/21_vision.learner.ipynb)

Screenshot 2022-07-25 at 23 00 23

**Comment by jph00** [comment]
Thanks @peterdudfield  -- I'm actually in the middle of updating fastai to work with nbdev2 and included your commit in that, so it'll be a while before it's visible! Your image looks like you figured it out though :)

**Comment by peterdudfield** [comment]
> Thanks @peterdudfield -- I'm actually in the middle of updating fastai to work with nbdev2 and included your commit in that, so it'll be a while before it's visible! Your image looks like you figured it out though :)

Thanks, and good luck changing it to nddev2. Its the first time ive seen this setup with notebooks, and then testing the notebooks. Looks good.

**Pull request closed without merging**
