### PR TITLE
Fix nan caused by missing classes in validation

### PR DESCRIPTION
**Pull request by KeremTurgutlu**
Adding epsilon to targets as well.

### CODE REVIEW

**Comment by KeremTurgutlu** [comment]
Looks like failed accuracy assertion:

```    def test_accuracy(learn):
        this_tests(accuracy)
>       assert accuracy(*learn.get_preds()) > 0.9
E       assert tensor(0.8941) > 0.9
E        +  where tensor(0.8941) = accuracy(*[tensor([[0.1554, 0.8446],\n        [0.3865, 0.6135],\n        [0.6020, 0.3980],\n        ...,\n        [0.5815, 0.4185],\n...0, 0, 0, 0, 0, 0, 0,\n        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n        0, 0, 0])])
E        +    where [tensor([[0.1554, 0.8446],\n        [0.3865, 0.6135],\n        [0.6020, 0.3980],\n        ...,\n        [0.5815, 0.4185],\n...0, 0, 0, 0, 0, 0, 0,\n        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n        0, 0, 0])] = <bound method Learner.get_preds of Learner(data=ImageDataBunch;\n\nTrain: LabelList (709 items)\nx: ImageList\nImage (3, 2... 1))\n  (10): ReLU(inplace)\n  (11): AdaptiveAvgPool2d(output_size=1)\n  (12): Flatten()\n)], add_time=True, silent=False)>()
E        +      where <bound method Learner.get_preds of Learner(data=ImageDataBunch;\n\nTrain: LabelList (709 items)\nx: ImageList\nImage (3, 2... 1))\n  (10): ReLU(inplace)\n  (11): AdaptiveAvgPool2d(output_size=1)\n  (12): Flatten()\n)], add_time=True, silent=False)> = Learner(data=ImageDataBunch;\n\nTrain: LabelList (709 items)\nx: ImageList\nImage (3, 28, 28),Image (3, 28, 28),Image (3, ..., 1))\n  (10): ReLU(inplace)\n  (11): AdaptiveAvgPool2d(output_size=1)\n  (12): Flatten()\n)], add_time=True, silent=False).get_preds

tests/test_vision_train.py:43: AssertionError```

**Comment by KeremTurgutlu** [comment]
Should I re-open this pull request?

**Comment by sgugger** [comment]
This is a random test, so it's jsut you being out of luck I think.

**Comment by KeremTurgutlu** [comment]
Yeah missed by 0.0060 :) I will re-open it then.

**Pull request closed without merging**
