### PR TITLE
Quick ClassConfusion fix and Documentation

### PR DESCRIPTION
**Pull request by muellerzr**
Tested it on images real quick and realized I had forgot something. My bad!

### CODE REVIEW

**Comment by muellerzr** [comment]
Finished the documentation too :) Let me know if there are issues. I wasn't 100% sure if I could include the other repository bit. The goal was to make it available, if there's a better way to go about that (like just having it on the forum and lead to the forum post instead let me know!)

**Comment by muellerzr** [comment]
(Promise we're good to go here, triple quadruple checked myself :) )

**Comment by sgugger** [comment]
Don't forget to run `tools/run-after-git-clone` in the repo because your notebooks aren't stripped out of their metadata.

**Comment by muellerzr** [comment]
Fixed the stripout issue.

**Comment by sgugger** [comment]
Looking good, thanks a lot!

**Pull request merged**
