### PR TITLE
AUC metric

### PR DESCRIPTION
**Pull request by SvenBecker**
Added the option to use AUC based on ROC for the binary classification task.
This implementation is very similar to the one provided by Sklearn but everything is done in PyTorch instead of Sklearn/NumPy.

Based on https://forums.fast.ai/t/use-auc-in-place-of-accuracy-as-loss/41168/3 or https://forums.fast.ai/t/using-auc-as-metric-in-fastai/38917/7 I thought it might be a nice feature to have.

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks, just put the docstring on one line. Merging this, can you please now add full documentation for these new functions in metrics.ipynb?

**Comment by tomfisher** [comment]
I tested with a tabular_learner for a binary classification problem, got the following error:

```
learn = tabular_learner(data, layers=[1024, 512, 256],  ps=[0.5, 0.7, 0.9],  loss_func=loss, metrics=[accuracy, auc_roc_score])


16  	    targ = targ[desc_score_indices]
 17  	    d = input[1:] - input[:-1]
 18  	    distinct_value_indices = torch.nonzero(d).transpose(0,1)[0]
 19  	    threshold_idxs = torch.cat((distinct_value_indices, LongTensor([len(targ) - 1])))
 20  	    tps = torch.cumsum(targ * 1, dim=-1)[threshold_idxs]
 21  ->	    fps = (1 + threshold_idxs - tps)
 22  	    if tps[0] != 0 or fps[0] != 0:
 23  	        fps = torch.cat((LongTensor([0]), fps))
 24  	        tps = torch.cat((LongTensor([0]), tps))
 25  	    fpr, tpr = fps.float() / fps[-1], tps.float() / tps[-1]
 26  	    return fpr, tpr
(Pdb) (threshold_idxs - tps).size()
*** RuntimeError: The size of tensor a (7109) must match the size of tensor b (2) at non-singleton dimension 1

```

**Comment by SvenBecker** [comment]
@tomfisher I did the testing only on `cnn_learner`. I assumed both would produce equally sized outputs and I didn't use tabular_learner so far to be honest. It might need some reshaping beforehand. I will take a look into this issue over the next week. I'm currently a little bit busy unfortunately.

@sgugger I'm working on it. Do you want
1. definitions, explanations and formulas for each single metric?
2. "how to use" examples like `auc=AUROC();cnn_learner(...,metrics=[auc],...)`? This might be a little bit repetitive?!
3. parameter clarification for each singe metric or rather some kind of referencing in case of parameter sharing.

Btw on a side note I would like to draw attention to
https://forums.fast.ai/t/part-2-2019-fellowship-invitations-and-some-special-thanks/39329/43, especially to the last couple of posts regarding the fastai v3 part II course selection procedure.

**Comment by sgugger** [comment]
Mainly an explanation of what they do with an example would be nice.

**Pull request merged**
