### PR TITLE
Fix anchors in the documentation

### PR DESCRIPTION
**Pull request by pouannes**

### CODE REVIEW

**Comment by pouannes** [comment]
I'm not really sure what the conflict is about, let me know if I need to change something.

**Comment by stas00** [comment]
Click on resolve conflicts, which takes you to:
 https://github.com/fastai/fastai/pull/1610/conflicts
and you can see what conflicts. Most likely you need to sync your branch with master (i.e. merge).

Also you asked about the `<b>` replacing `**` earlier, but that was inside the generated html files, the docbuilder does the replacing automatically. In the markdown we must use `**`. why do you have those happen in `.ipynb` files? Did you do it manually? It seems to only affect docs_src/metrics.ipynb

Also I see in the same file you use a custom kernel spec, which conflicts with the default we all use (weird diff below, but it's the last bits of  docs_src/metrics.ipynb in your commit)
```
  "kernelspec": {
   "display_name": "Python 3",
   "display_name": "Python (fastai-dev)",
   "language": "python",
   "language": "python",
   "name": "python3"
   "name": "fastai-dev"
  }
```

In docs_src/train.ipynb you added a new cell - probably unintentionally? or did you need it so that you could link to it?

The rest looks great!

**Comment by pouannes** [comment]
Thanks Stas ! About the docs_src/train.ipynb file, the new cell is indeed intentional (`ClassificationInterpretation` was moved there recently, and the linked were updated but there was no corresponding `show_doc`).

 I have no idea why the markdown got switched to html in metrics.ipynb, I didn't do it manually. I'll see what I can do. 

About the custom kernel it was my python  virtual env I needed to run the code and check it was working fine, I need to switch it back I suppose.

I'll fix the things you pointed out, thanks for the feedback !

**Comment by pouannes** [comment]
So I thought I fixed the mardown -> html bug but in fact I didn't... Any idea how I might fix this before I do it manually ?

**Comment by stas00** [comment]
wrt kernelspec "conflict" I posted some ideas [here](https://forums.fast.ai/t/git-an-easier-jupyter-notebook-modification-commit-process/20355/134), ideally it should be transparent to the user.

**Comment by stas00** [comment]
> So I thought I fixed the mardown -> html bug but in fact I didn't... Any idea how I might fix this before I do it manually ?

I don't know how it came about, did you execute that notebook and the conversions happened?

Do you by chance have some notebook extension that is activated and it did markdown2html?

Perhaps try with another notebook, or save this one and start from scratch and give me instructions on how I can reproduce what you did.

**Comment by pouannes** [comment]
All right I manually fixed it, should be all good now. 

I don't have nbextensions on the computer I used for this PR so no chance of this being caused by that. I think they happened because I executed some cells of that notebook. 

Also I didn't fix when the logs said ['list of duplicate or empty anchors'](https://dev.azure.com/fastdotai/fastai/_build/results?buildId=3222&view=logs&jobId=ab1d7d97-f2fc-5f83-3b83-0c83b70b5c97&taskId=25eeb179-0a91-54dd-3d6e-93ee7162a84d&lineStart=779&lineEnd=779&colStart=1&colEnd=36) because I didn't figure out what it was about.

**Comment by stas00** [comment]
Awesome work, @pouannes - thank you!

If you encounter that weird issue with md2html let's discuss it here: https://forums.fast.ai/t/documentation-improvements/32550

**Comment by pouannes** [comment]
Many thanks for your help and guidance @stas00 !

**Pull request merged**
