### PR TITLE
Disable progress ctx

### PR DESCRIPTION
**Pull request by bfarzin**
Adding a test to for the context manager functionality

### CODE REVIEW

**Comment by stas00** [comment]
why is `fastai/utils/mod_display.py` added again as a new file? Needing to rebase your fork?
https://docs.fast.ai/dev/git.html#how-to-keep-your-feature-branch-up-to-date

**Comment by stas00** [comment]
And the test error log is here:
https://dev.azure.com/fastdotai/fastai/_build/results?buildId=4341&view=logs
Did it pass on your side?

**Comment by bfarzin** [comment]
Yes. something is not right. All passed here, but seems to be wrong.  I think I got out of sync with Master.  Working on it now.

**Comment by stas00** [comment]
Also try this context in `lesson7-superres.ipynb`
this line:
```
 fastai.basic_train.master_bar, fastai.basic_train.progress_bar = fastprogress.force_console_behavior()
```
causes:

```
/mnt/nvme1/fast.ai-1/br/fastai/course-v3/nbs/dl1/fastai/basic_train.py in fit(epochs, learn, callbacks, metrics)
     97             cb_handler.set_dl(learn.data.train_dl)
     98             cb_handler.on_epoch_begin()
---> 99             for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
    100                 xb, yb = cb_handler.on_batch_begin(xb, yb)
    101                 loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)

~/anaconda3/envs/fastai/lib/python3.7/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update, txt_len)
    246         self.length = cols-txt_len
    247         self.max_len,self.prefix = 0,''
--> 248         super().__init__(gen, total, display, leave, parent, auto_update)
    249 
    250     def on_interrupt(self):

~/anaconda3/envs/fastai/lib/python3.7/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update)
     49         else:
     50             self.leave,self.display=False,False
---> 51             parent.add_child(self)
     52         self.comment = ''
     53         if not self.auto_update:

~/anaconda3/envs/fastai/lib/python3.7/site-packages/fastprogress/fastprogress.py in add_child(self, child)
    198     def add_child(self, child):
    199         self.child = child
--> 200         self.inner_dict['pb2'] = self.child.progress
    201         self.show()
    202 

AttributeError: 'ConsoleProgressBar' object has no attribute 'progress'
```

in the first lr_find call there.

**Comment by stas00** [comment]
Also x.func doesn't exist in unet_learner, so I have reworked your context to check that it exists. will commit shortly (and abstracted the functionality out to be used outside of context manager)

**Comment by stas00** [comment]
Here is the new version of StopAfterNBatches (not yet committed):
```
" Miscellaneous callbacks "

from ..basic_train import LearnerCallback
from fastai.utils.mod_display import progress_disabled_ctx

class StopAfterNBatches(LearnerCallback):
    "Stop training after n batches of the first epoch."
    def __init__(self, learn, n_batches:int=2):
        self.n_batches = n_batches-1 # iteration starts from 0
        self.prog_ctx = progress_disabled_ctx(learn)

    def on_batch_end(self, iteration, **kwargs):
        if iteration == self.n_batches:
            return {'stop_epoch': True, 'stop_training': True, 'skip_validate': True}

    def on_train_begin(self, **kwargs): self.prog_ctx.disable()
    def on_train_end(self, **kwargs):   self.prog_ctx.enable()
```

note you have to configure it differently now:

    # 1. global assignment
    defaults.extra_callback_fns = [partial(StopAfterNBatches, n_batches=run_n_batches)]

    # 2. dynamic assignment
    learn = fake_learner(train_length=train_length, batch_size=bs)
    learn.callback_fns.append(partial(StopAfterNBatches, n_batches=run_n_batches))

**Comment by bfarzin** [comment]
Took me a couple tries to re-base.  I can see why I want to avoid that whenever I can!  
Thanks for your help and guidance.  Let me run more test cases and assure that things do not fail here.

**Comment by bfarzin** [comment]
`lesson7-superres.ipynb` runs as it with the context manager that is pushed out there.  No updates are put out, but I do get new trained values.  So that is as expected.  

I added your new `StopAfterNBatches` and I replicate your error locally.  Working on addressing that now.  

Should we check in the new `StopAfterNBatches` along with this change/update?

**Comment by stas00** [comment]
Thank you, @bfarzin.

So far now I will hold off integrating this ctx manager into StopAfterNBatches, since Sylvain is planning on a much simpler API that could be done globally.

So I will unroll those functions back to how you initially did it.

**Comment by stas00** [comment]
> Should we check in the new StopAfterNBatches along with this change/update?

Let's just leave it for now, and come back to it after part 2.

Otherwise we need to break the API and Sylvain says it won't be needed when he reworks it. I pushed my wip into a branch here: https://github.com/fastai/fastai/tree/StopAfterNBatches-learner

**Comment by bfarzin** [comment]
ok.  Thank you for the update.  We can address when that is pushed later

**Comment by stas00** [comment]
And I linked the doc to the menu bar and fixed the outdated API
https://docs.fast.ai/utils.mod_display.html
so this is complete now.

Thanks again

**Pull request merged**
