### PR TITLE
Add explicit links to the migrating scripts [Documentation]

### PR DESCRIPTION
**Pull request by muellerzr**
Makes sure that each Migrating* tutorial has an explicit link to the various script they utilize

### CODE REVIEW

**Comment by jph00** [comment]
The links are only needed for folks using Colab. So I'd suggest saying something like they're "in the `examples` subdirectory of this folder, if you checked out the repo from git, or can be downloaded from [here](...) if you're using an online viewer such as Colab."

**Comment by muellerzr** [comment]
Makes sense, will make that adjustment today

**Comment by jph00** [comment]
> Makes sense, will make that adjustment today

Any news?

**Comment by muellerzr** [comment]
Yup! Sorry, life got busy unexpectedly. Will push some changes in an hour
or so.

**Comment by muellerzr** [comment]
@jph00 made adjustments. Went with:

> Note: The source script for `X` is in the `examples` subdirectory of this folder if you checked out the `fastai` repo from git, or can be downloaded from [here](https://github.com/fastai/fastai/blob/master/nbs/examples/X.py) if you're using an online viewer such as Colab.

**Pull request merged**
