### PR TITLE
Add documentation for fastai.imports

### PR DESCRIPTION
**Pull request by ericricky**
I wrote a quick reference for the convenience imports that are pulled in whenever using a star import on a fastai module. This kind of documentation can help Python beginners get exposure to functions and libraries that experienced programmers find useful. It also should be helpful to have a compact list of these imports with links to documentation. I'm not sure where this would go, maybe under the "core" docs.

### CODE REVIEW

**Comment by sgugger** [comment]
This is looking good and is a good idea. @stas00 can you link to it under core (last item)? I think that would be a good place for it indeed.

**Comment by stas00** [comment]
Done: https://docs.fast.ai/imports.html

The only issue is how to keep that page up-to-date - since it was created manually very quickly it'll become outdated...

**Comment by ericricky** [comment]
Looks good, thanks!

**Comment by stas00** [comment]
Committed.

**Pull request merged**
