### PR TITLE
Uncommented cells of the Transformers tutorial

### PR DESCRIPTION
**Pull request by husainhz7**
Was going through the Transformers tutorial and was mildly annoyed at empty cells. Just a minor change.

### CODE REVIEW

**Comment by jph00** [comment]
If you're uncommenting the cells, then you should run them so the outputs are included in the docs! :)

**Review by jph00 — CHANGES_REQUESTED** [review]
Include outputs in notebook.

**Comment by jph00** [comment]
Looks like you need to run `nbdev_clean_nbs`.

**Comment by husainhz7** [comment]
Yeah was having trouble setting it up for some reason. I thought I could get away with it.

**Comment by jph00** [comment]
Feel free to ask if you have trouble getting nbdev working OK. Many thanks for the PR.

**Pull request merged**
