### PR TITLE
Fix broken links in README.md

### PR DESCRIPTION
**Pull request by rushabh-v**
Fixes: https://github.com/fastai/fastai/issues/2731

### CODE REVIEW

**Comment by hamelsmu** [comment]
@rushabh-v the README is updated through `index.iypnb` don't update the README directly.

**Comment by hamelsmu** [comment]
I'll go ahead and close this PR, please feel free to open a new one with changes to `index.ipynb`

**Comment by rushabh-v** [comment]
Thanks for the clarification!

Seems a problem in converting the links specifically pointing to `https://docs.fast.ai/<x.html>` by `nbdev` as all the links in `index.ipynb` are in fact appropriate.

I am looking into it!

**Comment by rushabh-v** [comment]
I think until the issue with `nbdev` is fixed we should manually make this change in README. (if that's allowed)

WDYT? @hamelsmu

**Comment by rushabh-v** [comment]
It has been addressed here: https://github.com/fastai/nbdev/issues/223

I think we just need to use `nbdev==1.0.5`

**Comment by hamelsmu** [comment]
Yeah I think we should fix the changes in nbdev first

is the most current version of nbdev not being used here?  I think it is?

**Comment by rushabh-v** [comment]
https://github.com/fastai/fastai/blob/master/settings.ini#L19

**Pull request closed without merging**
